### ISSUE TITLE
Fix external class links in Reference docs

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#2451] opened 2017-09-18 23:26 UTC
http://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/com/google/cloud/language/v1/LanguageServiceSettings.html

does not link correctly to classes like `com.google.cloud.language.v1.AnalyzeEntitySentimentRequest`
`com.google.cloud.language.v1.AnalyzeEntitySentimentResponse`
in the Java docs.

I thought we had fixed this the last time ?

FYI @nnegrey

**Comment by pongad** [comment] 2017-09-19 06:15
@neozwu Could you look into this? I think this is caused by us not creating javadocs for protos. The [last commit](https://github.com/googleapis/googleapis/tree/gh-pages/java) to Java proto docs was 7 days ago

**Comment by neozwu** [comment] 2017-09-19 18:57
I have created Proto docs and republished google-cloud-java docs. Close this as the issue should be fixed now.

**Closed by neozwu** 2017-09-19 18:57 UTC
