### ISSUE TITLE
GCS Upload failure from CRC32C mismatch

### ISSUE THREAD

**Issue by josephui** [GoogleCloudPlatform/google-cloud-java#2099] opened 2017-05-31 20:12 UTC
While uploading files on via `google-cloud-storage 1.0.2` / `java 8`, infrequently there are error messages indicating that a file has failed to upload due to CRC32C mismatch (where the calculated CRC32C=`AAAAAA==`, see [this](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java#L83).

Sample code we used to produces this:
```
void uploadToGcs (String path, byte[] content, String mimeType, String cacheControl) {
	Builder blobBuilder = BlobInfo.newBuilder(getBucketName(), path);
	blobBuilder.setCacheControl(cacheControl);
	blobBuilder.setContentType(mimeType);
	BlobInfo blob = blobBuilder.build();

	try {
		storageClient.create(blob, content);
	} catch (StorageException e) {
		LOG.error("Failed to upload: " + path);
		throw e;
	}
}
```

Logs:
```
May 31 11:56:48 Uploading File: my-folder-1/test_file_882 on thread 1, size: 408148 bytes
May 31 11:56:48 Uploading File: my-folder-2/test_file_882 on thread 2, size: 408148 bytes
May 31 11:56:53 Uploading File: my-folder-2/test_file_883 on thread 2, size: 354568 bytes
May 31 11:56:57 Uploading File: my-folder-2/test_file_884 on thread 2, size: 315652 bytes
May 31 11:57:01 Uploading File: my-folder-2/test_file_885 on thread 2, size: 394800 bytes
May 31 11:57:05 Uploading File: my-folder-2/test_file_886 on thread 2, size: 391980 bytes
May 31 11:57:09 Failed to upload: my-folder-1/test_file_882 on thread 1
May 31 11:57:09 ERROR - restarting runner: : com.google.cloud.storage.StorageException: Provided CRC32C "eThpEg==" doesn't match calculated CRC32C "AAAAAA==".|at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:189)|at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:240)|at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:151)|at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:148)|at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:93)|
May 31 11:57:09 Uploading File: my-folder-2/est_file_887 on thread 2, size: 322984 bytes
May 31 11:57:12 Uploading File: my-folder-2/est_file_888 on thread 2, size: 429204 bytes
May 31 11:57:13 Uploading File: my-folder-1/est_file_882 on thread 1, size: 408148 bytes
May 31 11:57:13 Uploading File: my-folder-1/est_file_883 on thread 1, size: 354568 bytes
May 31 11:57:13 Uploading File: my-folder-1/est_file_884 on thread 1, size: 315652 bytes
```

The uploading is done with two threads uploading files sequentially (a file is generated every 4 seconds), note that `thread 2` continue to upload successfully for the duration of the error in `thread 1`, thus we can rule out general connectivity issue. Also note that it took a long time (21 seconds) for the error to bounce back.

Can anyone shed light to this behavior?
Thanks!

**Comment by josephui** [comment] 2017-06-12 20:39
@garrettjonesgoogle Please let me know if there are anything else I can provide to help with the investigation.

**Comment by mkrufky** [comment] 2017-07-28 16:57
I am seeing this same issue in the golang client client library `cloud.google.com/go/storage` . I believe this issue is cloud-side raher than sdk-side

**Comment by tcoffee-google** [comment] 2017-07-28 21:04
I was not able to reproduce the problem from @josephui 's example, using random data files of similar size. This suggests to me the problem may be data-dependent.

Per @mkrufky 's https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2099#issuecomment-318707288, I suggest opening an issue [tagging the API on StackOverflow](https://stackoverflow.com/questions/tagged/google-cloud-storage).

**Comment by garrettjonesgoogle** [comment] 2017-08-16 23:58
According to b/64605503 , when retrying 503 errors, sometimes 0 bytes are sent instead of the original set of bytes. Re-opening to investigate.

**Comment by vam-google** [comment] 2017-08-17 00:08
This comment https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2099#issuecomment-318707288 implies that there is similar behavior for golang client. Seems suspicious that 2 different clients have same bug.

Also, regarding Storage retries on 503, there was a recent bug about retrying on 503 not working at all in java client library https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2098. 

It is worth mentioning that Java Veneer clients send requests with "Accep" header which prefers text/html content over application/json (the 503 retrying bug was caused by receiving text response instead of json from the server in case of 503 error code).

**Comment by garrettjonesgoogle** [comment] 2017-08-18 21:22
Fixed by https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2359 . We will make a release for this soon.

**Closed by garrettjonesgoogle** 2017-08-18 21:22 UTC
Labels: API: storage, Priority: P1, Type: Bug
