### ISSUE TITLE
Fix large memory usage

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1907] opened 2017-04-12 20:14 UTC

**Comment by garrettjonesgoogle** [comment] 2017-04-12 20:27
@vam-google : for this, we want to at least figure out what the cause might be before GA; after we figure out the cause, we can then decide if we want to actually fix it before GA or not.

**Comment by meltsufin** [comment] 2017-04-19 20:12
@vam-google Can you also look into the breakdown between heap and off-heap memory usage as part of this?

**Comment by vam-google** [comment] 2017-04-20 20:42
Profiling is completed.
@meltsufin the results are sent to your mailbox, including the non-heap usage results.

**Comment by vam-google** [comment] 2017-04-20 23:47
The found memory issues are test-related and are not present in the actual clients code.

**Comment by vam-google** [comment] 2017-05-05 21:23
Closing as the memory issues are caused by testing code only.

**Closed by vam-google** 2017-05-05 21:23 UTC
