### ISSUE TITLE
PubSub not returning any instance.

### ISSUE THREAD

**Issue by vaibhavswarnkar** [GoogleCloudPlatform/google-cloud-java#1510] opened 2017-01-06 08:40 UTC
I'm using Cloud PubSub and trying to get access to the PubSub locally using Service Account JSON credential, but it is not returning anything. Below is the code I'm using to get PubSub instance. Neither it is throwing any exception nor it is returning any PubSub instance. This is an issue which needs to be resolved urgently, anyone can help me.

```
private PubSub getPubSubForLocal() {

        PubSub pubSub = null;
        InputStream inputStream = getClass().getResourceAsStream("/cloud/vostics-cloud-e56ac878e27e.json");
        try {
            pubSub = PubSubOptions.newBuilder()
                    .setCredentials(ServiceAccountCredentials.fromStream(inputStream))
                    .build()
                    .getService();

        } catch (IOException e) {
            return null;
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        return pubSub;
    }

```

**Comment by garrettjonesgoogle** [comment] 2017-01-06 15:52
Is it throwing an IOException? Your code converts that to `null`.

**Comment by vaibhavswarnkar** [comment] 2017-01-06 16:16
@garrettjonesgoogle It is throwing any exception either.

**Comment by vaibhavswarnkar** [comment] 2017-01-06 16:16
@garrettjonesgoogle Also, in other application it is giving me an error with code 443.

**Comment by garrettjonesgoogle** [comment] 2017-01-06 16:30
So I think I need to understand what you mean by "it is not returning anything." Only one of the following is possible:

1. The return value is `null`
2. The return value is a PubSub object
3. An exception is thrown
4. The JVM crashes such that the function didn't return

Which of those is happening?

**Comment by vaibhavswarnkar** [comment] 2017-01-07 07:38
@garrettjonesgoogle Alright, this may sound weird because it is to me.

I've two applications in place and to make them communicate with each other I'm using PubSub, above code is common in both of the application to get an instance of PubSub. In one application it is giving below error:

`07-Jan-2017 12:48:56.238 INFO [RMI TCP Connection(3)-127.0.0.1] io.grpc.internal.ManagedChannelImpl.<init> [ManagedChannelImpl@1d98cfab] Created with target pubsub.googleapis.com:443`

In another application it is not returning anything, now when I'm saying it is not returning anything by that I mean that it is neither throwing any exception nor returning PubSub object.

I've tried debugging my code and when executing the code, IDE never reaches to the exception part.

**Comment by vaibhavswarnkar** [comment] 2017-01-07 20:25
@garrettjonesgoogle Can you help me, I need to resolve this ASAP.

**Comment by garrettjonesgoogle** [comment] 2017-01-09 16:04
Ok I think I should have included another possibility:

5. One of the function calls hangs, so it never returns.

Can you use your debugger to step into the google-cloud-java code to see more specifically where it is hanging?

**Comment by vaibhavswarnkar** [comment] 2017-01-10 09:08
@garrettjonesgoogle I've solved this issue, but now whenever I'm trying to get topic or create topic, it is giving me error saying DEADLINE_EXCEDDED.

**Comment by garrettjonesgoogle** [comment] 2017-01-10 22:55
1. I'm curious to know if you can say what caused your issue, in case others come across it.
2. Generally DEADLINE_EXCEEDED is caused by the static netty-tcnative dependency not loading. See https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1430 for one particular example. I would need to know more about your environment to help you with that. Could you also turn on FINE logging and provide the library loading errors you see?

**Comment by vaibhavswarnkar** [comment] 2017-01-11 06:35
@garrettjonesgoogle 
1. It was the issue with my classpath, input stream wasn't able to find the JSON file.
2. I've added nitty-all dependency in my project, but still error is there.

**Comment by garrettjonesgoogle** [comment] 2017-01-26 17:45
@vaibhavswarnkar In order to help with # 2, could you provide the details of your environment (exact OS version & setup in particular), and errors that you see when you set the logging level to FINE?

**Comment by vaibhavswarnkar** [comment] 2017-01-27 13:28
@garrettjonesgoogle My problem has been solved. I changed my Spring MVC app to Spring boot app and even after that it wasn't working then I changed the server to jetty server and it worked.

**Comment by garrettjonesgoogle** [comment] 2017-01-27 15:22
Great! Closing out issue now.

**Closed by garrettjonesgoogle** 2017-01-27 15:22 UTC
Labels: pubsub
