### ISSUE TITLE
longRunningRecognizeAsync return SpeechRecognitionResult  whit Alternatives different from first have word list empty

### ISSUE THREAD

**Issue by bud4** [GoogleCloudPlatform/google-cloud-java#3316] opened 2018-05-28 14:29 UTC
```
// after  longRunningRecognizeAsync 
// with setMaxAlternatives to 6
for ( SpeechRecognitionAlternative alt :  result.getAlternativesList()) {
    alt.getConfidence(); // is ok full
    alt.getTranscript(); // is ok full
      	for ( WordInfo word : alt.getWordsList() ) { // NOT ok word list is empty after first ..     
		//speechRecognitionAlternative
		ParolaTrascrizione parola = new ParolaTrascrizione(word);
		listParole.add(parola);
	}
}
```

**Comment by andreamlin** [comment] 2018-06-04 18:47
Hello,

Would you mind providing more clarification on the exact nature of the problem, where it fails, and what `ParolaTrascrizione` is?

**Comment by hzyi-google** [comment] 2018-06-06 19:12
Hi, in order for the `alternatives` in `SpeechRecognitionResult` to include a list of `WordInfo`, please enable it in `RecognitionConfig`:

```
RecognitionConfig config =
    RecognitionConfig.newBuilder()
        .setEnableWordTimeOffsets(true)
        ... // other settings
        .build();
```
I am closing this issue, but feel free to let us know if you have further questions.

**Comment by bud4** [comment] 2018-06-06 19:53
ParolaTrascrizione iis my class. it is not relevant.
I enable WordTimeOffsets in RecognitionConfig .
the problem is that the word list is only present in the first occurrence of the cycle not in the successive ones.  
Please reopen
example :
//index 0 ok
result.getAlternativesList().get(0).getTranscript()  // String is not empty ok 
result.getAlternativesList().get(0).getWordsList(); // list is not empty ok
//index 1 inconsistency  
result.getAlternativesList().get(1).getTranscript()  // String is not empty ok 
result.getAlternativesList().get(1).getWordsList(); // list is  empty !!!! Error

**Comment by bud4** [comment] 2018-06-06 19:56
Please reopen ..
ParolaTrascrizione iis my class. it is not relevant.
I enable WordTimeOffsets in RecognitionConfig .
the problem is that the word list is only present in the first occurrence
of the cycle not in the successive ones.

example :
//index 0 ok
result.getAlternativesList().get(0).getTranscript() // String is not empty
ok
result.getAlternativesList().get(0).getWordsList(); // list is not empty ok
//index 1 inconsistency
result.getAlternativesList().get(1).getTranscript() // String is not empty
ok
result.getAlternativesList().get(1).getWordsList(); // list is empty !!!!
Error

----------------------------------------------------------------

*«L'immaginazione è più importante della conoscenza.» - Albert Einstein.*



*Alberto M.Fiaschi*



*http://it.linkedin.com/pub/alberto-fiaschi
<http://it.linkedin.com/pub/alberto-fiaschi/38/783/a5> *

2018-06-06 21:12 GMT+02:00 Hanzhen Yi <notifications@github.com>:

**Comment by hzyi-google** [comment] 2018-06-06 20:15
Hi,
Thanks for clarifying that. However it seems `speech` only provides time offset information for the top result according to [this](https://cloud.google.com/speech-to-text/docs/reference/rest/v1/RecognitionConfig). This seems to be an intended behavior of the server side.

**Comment by bud4** [comment] 2018-06-06 21:33
Thanks. I see now

Il mer 6 giu 2018, 22:15 Hanzhen Yi <notifications@github.com> ha scritto:

**Closed** 2018-06-07 00:00 UTC
Labels: api: speech, priority: p2, type: question
