### ISSUE TITLE
Java client BigQuery.getTable returns a table with null schema when the table has no field

### ISSUE THREAD

**Issue by cakraww** [GoogleCloudPlatform/google-cloud-java#2477] opened 2017-10-04 03:05 UTC
To reproduce,
1. Create an empty BigQuery table without any field on its schema. Let's say it's table "tableA" on dataset "dataset1".
2. Running this code fails the assertion.
```
    BigQuery bigQuery = BigQueryOptions.getDefaultInstance().getService();
    Table table = bigQuery.getTable("dataset1", "tableA");
    Assert.assertNotNull(table.getDefinition().getSchema());
```

Is this expected behavior? Because we in fact can't create a TableDefinition with null schema as it's null-checked in `com.google.cloud.bigquery.TableDefinition.Builder`.
```
    /**
     * Sets the table schema.
     */
    public B setSchema(Schema schema) {
      this.schema = checkNotNull(schema);
      return self();
    }
```
I think `BigQuery.getTable` on a table with empty schema should return a Schema instance with no field within its TableDefinition.

**Comment by pongad** [comment] 2017-10-06 05:33
@vam-google @tswast Would you be able to look into this?

A quick fix for this is to add
```java
if (schema == null) return Schema.of();
```
It feels a little hacky to be able to leave the field null though.

Making the field non-null broke a bunch of tests, so I'm not sure if leaving the field nullable was a deliberate choice.

**Comment by tswast** [comment] 2017-10-06 17:41
The way the [Tables API](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables) was designed leaves it a bit ambiguous, I admit.

The relevant portion in the API:

```
  "schema": {
    "fields": [
      {
        "name": string,
        "type": string,
        "mode": string,
        "fields": [
          (TableFieldSchema)
        ],
        "description": string
      }
    ]
  },
```

Since `schema` is an optional object, it can indeed be omitted in responses or null. I think it would have been better if `schema` was just a repeated list of field, but this is what we have, so we do need to handle nulls in a sane way.

I believe Python handles this by defaulting to an empty list if `schema` is null or undefined.

**Comment by tswast** [comment] 2017-10-06 17:42
:+1: on making the field non-nullable.

**Closed** 2017-10-23 03:48 UTC
Labels: API: bigquery
