### ISSUE TITLE
Provide a way to create a TableDefinition from a schema file

### ISSUE THREAD

**Issue by esanchezros** [GoogleCloudPlatform/google-cloud-java#2308] opened 2017-08-05 20:59 UTC
It would be useful to have a way to create a TableDefinition from a schema file. For example something like:

```
Schema schema = Schema.fromFile(schemaFile);
TableDefinition tableDefinition = StandardTableDefinition.of(schema);
```

**Comment by NicolaSpreafico** [comment] 2018-01-07 09:48
While the question seems to be unchanged since 7 Aug, I wrote a custom deserializer which allow to deserialize a json schema to` com.google.cloud.bigquery.Schema` object

You can find the source here
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2753

**Comment by vam-google** [comment] 2018-01-11 00:19
Closing this as a duplicate of https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2553 (which was created later, but has a wider scope, that is why keeping it).

**Closed by vam-google** 2018-01-11 00:19 UTC
Labels: api: bigquery, priority: p2, type: feature request
