### ISSUE TITLE
broken design on documentation site

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/google-cloud-java#2664] opened 2017-11-27 19:18 UTC
See the 'google-cloud' title on 
https://googlecloudplatform.github.io/google-cloud-java/0.30.0/index.html

<img width="1432" alt="screen shot 2017-11-27 at 11 17 25 am 1" src="https://user-images.githubusercontent.com/360895/33284641-9b24e124-d364-11e7-9151-bd4730363496.png">

**Comment by pongad** [comment] 2017-12-07 00:44
Duplicate of #2663

**Closed by pongad** 2017-12-07 00:44 UTC
