### ISSUE TITLE
Datastore - Too many external HttpURLConnection[datastore.googleapis.com] calls

### ISSUE THREAD

**Issue by brunovieira7** [GoogleCloudPlatform/google-cloud-java#2481] opened 2017-10-04 17:28 UTC
I have a java API on **GAE** using the **google-cloud-datastore** client as presented in the documentation. Measuring with newrelic why some requests were taking so long I found out that a single "get by key" makes 6 url connections to **datastore.googleapis.com** is this correct?

_the code is as simple as the examples:_

`private final Datastore datastore = DatastoreOptions.getDefaultInstance().getService();`
...
`datastore.get(datastore.newKeyFactory().setKind("kind").setNamespace("namespace")
                .addAncestor(PathElement.of(("parent"), parentId))
                .newKey(key));`

_heres the evidence:_
<img width="750" alt="captura de tela 2017-10-04 as 12 56 20" src="https://user-images.githubusercontent.com/24440172/31189873-d4e56bec-a90f-11e7-9c1f-a09636c9bad9.png">

**Comment by pongad** [comment] 2017-10-06 06:29
@brunovieira7 Thank you for the report. Unfortunately, I cannot reproduce this.

I ran the following code, which is pretty similar to yours:
```java
final Datastore datastore = DatastoreOptions.getDefaultInstance().getService();
    KeyFactory keyFactory =
        datastore
            .newKeyFactory()
            .setKind("Person")
            .setNamespace("namespace")
            .addAncestor(PathElement.of("parentkind", "parent"));
    Key key = keyFactory.newKey("john.doe@gmail.com");
    Entity entity = Entity.newBuilder(key)
        .set("name", "John Doe")
        .set("age", 51)
        .set("favorite_food", "pizza")
        .build();
    datastore.put(entity);

    for (int i = 0; i < 10; i++) {
      long milli = System.currentTimeMillis();
      System.out.println(datastore.get(key));
      System.out.println(System.currentTimeMillis() - milli);
    }
```

In all iterations except the first, `get` takes less than 500ms.
To make sure, I also "hacked" this file to print "call" every method and verified that each iteration makes only 1 call.

Could you try running code similar to mine (maybe in GCE instance)? Maybe the data you're storing is triggering something I'm not seeing.

I noticed that you also have 6 calls to "accounts.google.com", is this a coincidence?

**Comment by brunovieira7** [comment] 2017-10-09 13:17
The performance is not an issue since when I breakdown the calls to "datastore.googleapis.com" **each** call does not take that long.

I can only see those internal client calls using the newrelic agent. It detects external calls from the API and measures the time it takes. I don't know what the client is doing under the hood, just think it's odd to make 6 calls for a get.

the calls to "accounts.google.com" might be some authentication stuff, it only happens in my first request

I did run your code on my API just to check as you said if it was some problem with my data but it appears it is not:

<img width="755" alt="captura de tela 2017-10-09 as 10 13 18" src="https://user-images.githubusercontent.com/24440172/31339931-ce798314-acda-11e7-9d1b-cf03490a7e81.png">

**Comment by pongad** [comment] 2017-10-11 23:18
Looking at the [code](https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/d9877c1cbc399d5ec9dd43ebb6a849f7d35b968a/java/datastore/src/main/java/com/google/datastore/v1/client/Datastore.java#L58) actually doing the RPC call but quite baffled how the factor of 6 is coming from. I've reached out to Datastore team who has more experience with this.

**Comment by pongad** [comment] 2017-10-13 01:14
@brunovieira7 Datastore client had a bug where connections are not reused which results in an SSL handshake every request. This has been recently fixed, so I'd expect that the client will perform better the next release. We don't think this explains the 6 calls though.

New Relic is a black box for us; without knowing how it counts calls, it's difficult to debug. In [this branch](https://github.com/pongad/google-cloud-java/tree/datastore-log), I added some instrumentation that prints how many RPCs Datastore client thinks it has made after every call to a lookup. Could you run it and let us know what it prints? (It will print the total number of calls since the client was created, not after the last print.)

On my machine, it prints 11 (1 put + 10 gets). If it prints the same on your setup, then I suspect that New Relic is counting number of calls differently from what we expect.

**Comment by brunovieira7** [comment] 2017-10-16 16:48
Just did that and it prints the same here as it did in your tests, 11. I don't know if the connection reuse fix came with 1.8.0 but I tried that version as well and it still gives me 6 calls per access

**Comment by Temikus** [comment] 2017-10-17 00:59
@pongad called me into this thread as I've had a bit of experience with NewRelic before.
@brunovieira7 We'll likely need some additional information to figure out where the counts are originating from.

From the looks of it the screenshot provided looks like an overview screen of a "Transaction Trace" You should be able to go to "trace details" screen to view where those components showed up within the transaction if I remember correctly. Would it be possible to provide a transaction trace here in a gist so we can see a bit more into how the requests originated? You can obfuscate any information you deem proprietary.

It would be even better if you could switch the Java agent to `FINEST` level before doing that as that'll yield more data for us (and you) to trace the behaviour. NOTE:  Please note this is a VERY verbose log level so you may want to consider minimizing the runtime in a production environment and use a test or staging environment if possible.

**Comment by brunovieira7** [comment] 2017-10-17 15:38
@Temikus thats the transaction breakdown, what it does is exactly the code @pongad asked me to try out. The only other thing I can do is zooming in the particular External segment **HttpURLConnection[datastore.googleapis.com]** which doesn't say much. (I'm including those screenshots as well, just in case)

I also did what you asked, log wise. Maybe you guys can detect something so I'm sending it as well. I made 2 calls (first one unrelated) so I marked in the log file with "**STARTS HERE**" where the call with the 11 datastore calls start.

[newrelic_agent.log](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1391595/newrelic_agent.log)

<img width="1216" alt="captura de tela 2017-10-17 as 13 16 34" src="https://user-images.githubusercontent.com/24440172/31674211-013bc7ce-b340-11e7-97f1-477702aeeacd.png">
<img width="743" alt="captura de tela 2017-10-17 as 13 17 10" src="https://user-images.githubusercontent.com/24440172/31674214-02bcab5e-b340-11e7-824a-68d35191dc46.png">

**Comment by pongad** [comment] 2017-10-18 09:06
@brunovieira7 @Temikus 
I did more investigation, this time looking directly at TCP packets.

**Test setup**
I modified the test script. Now it does not create an entity; it just looks up an entity once. (otherwise there'd be too many packets to look at.)

On my dev machine, I used wireshark with filter "host datastore.googleapis.com".

**Results**
Throughput the run of the test program, Wireshark reports 23 TCP packets. The first 13 were used to set up the TCP connection and SSL handshake.

Packets 14-15: we send the request to the server
Packets 16-17: the server acks
Packets 18-19: the server sends back the response
Packets 19-23: we ack, then tear down the connection.

I reran the test on a GCE instance, with `tcpdump` this time. The dump shows 25 packets. I couldn't 
(or didn't know how to) inspect the packets as I did with Wireshark, but it showed one packet with bad checksum, so that probably explains the difference in number of packets.

**Thoughts**
I really suspect that New Relic is somehow misreporting the number. I don't want to randomly point fingers, but the investigation suggests there aren't enough TCP packets to form 6 separate HTTP requests.

@brunovieira7 At this point, could you try out version `1.8.0` and let us know if we're still being too slow? (On my desktop, the first call to `get()` takes >1s but subsequent calls all take <500ms; on version `1.7.0` subsequent calls take ~800ms.) I

**Comment by aalexand** [comment] 2017-10-18 15:24
@pongad Out of curiousity, what was the commit / PR that fixed the connection reuse issue?

**Comment by pongad** [comment] 2017-10-18 20:25
@aalexand It was fixed in the lower-level Datastore client that we wrap. The lower level client fixed it in [this PR](https://github.com/GoogleCloudPlatform/google-cloud-datastore/pull/181), and we updated the dependency [here](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2508)

**Comment by brunovieira7** [comment] 2017-10-24 12:32
@pongad 1.8.0 looks slightly faster, I'll definitely use it. Since we couldn't find where the calls are coming from maybe NewRelic is misreporting. Thanks for all the help guys.

**Comment by pongad** [comment] 2017-10-24 22:38
@brunovieira7 Glad to hear you're seeing improvements! That is my assumption right now, so I'll close the issue. Please reopen if required.

**Closed by pongad** 2017-10-24 22:38 UTC
Labels: API: datastore, performance
