### ISSUE TITLE
1.0.0 Datastore & 0.17.1-alpha don't play well together

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#2020] opened 2017-04-29 07:39 UTC
In my pom.xml:
```
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-pubsub</artifactId>
      <version>0.17.1-alpha</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-datastore</artifactId>
      <version>1.0.0</version>
    </dependency>
```
Errors:

[ERROR] Failed to execute goal on project flexible-pubsub: 
Could not resolve dependencies for project 
com.example.flexible:flexible-pubsub:war:1.0-SNAPSHOT: Failed to collect dependencies for com.example.flexible:flexible-pubsub:war:1.0-SNAPSHOT: Could not resolve version conflict among [com.google.cloud:google-cloud-pubsub:jar:0.17.1-alpha -> com.google.cloud:google-cloud-core-grpc:jar:1.0.0 -> io.grpc:grpc-protobuf:jar:1.2.0 -> io.grpc:grpc-core:jar:1.2.0, com.google.cloud:google-cloud-pubsub:jar:0.17.1-alpha -> com.google.cloud:google-cloud-core-grpc:jar:1.0.0 -> io.grpc:grpc-protobuf:jar:1.2.0 -> io.grpc:grpc-protobuf-lite:jar:1.2.0 -> io.grpc:grpc-core:jar:1.2.0, com.google.cloud:google-cloud-pubsub:jar:0.17.1-alpha -> io.grpc:grpc-netty:jar:1.2.0 -> io.grpc:grpc-core:jar:[1.2.0,1.2.0], com.google.cloud:google-cloud-pubsub:jar:0.17.1-alpha -> io.grpc:grpc-stub:jar:1.2.0 -> io.grpc:grpc-core:jar:1.2.0, com.google.cloud:google-cloud-pubsub:jar:0.17.1-alpha -> io.grpc:grpc-auth:jar:1.2.0 -> io.grpc:grpc-core:jar:[1.2.0,1.2.0], com.google.cloud:google-cloud-datastore:jar:1.0.0 -> com.google.cloud.datastore:datastore-v1-protos:jar:1.3.0 -> com.google.api.grpc:grpc-google-common-protos:jar:0.1.0 -> io.grpc:grpc-all:jar:1.0.1 -> io.grpc:grpc-protobuf-nano:jar:1.0.1 -> io.grpc:grpc-core:jar:1.0.1, com.google.cloud:google-cloud-datastore:jar:1.0.0 -> com.google.cloud.datastore:datastore-v1-protos:jar:1.3.0 -> com.google.api.grpc:grpc-google-common-protos:jar:0.1.0 -> io.grpc:grpc-all:jar:1.0.1 -> io.grpc:grpc-core:jar:[1.0.1,1.0.1], com.google.cloud:google-cloud-datastore:jar:1.0.0 -> com.google.cloud.datastore:datastore-v1-protos:jar:1.3.0 -> com.google.api.grpc:grpc-google-common-protos:jar:0.1.0 -> io.grpc:grpc-all:jar:1.0.1 -> io.grpc:grpc-okhttp:jar:1.0.1 -> io.grpc:grpc-core:jar:[1.0.1,1.0.1]] -> [Help 1]

**Comment by lesv** [comment] 2017-04-29 15:11
After sleeping on it, I realized that this isn't as big a deal as I was thinking.  (we just need to tell people you can't mix GA and non-GA.  We should talk about this however.

**Comment by lesv** [comment] 2017-04-29 15:20
Argh - You haven't published a 0.17.1-alpha for Datastore.  Now, I'm just unhappy.  I'll try to use the big single jar, but this doesn't work.

**Comment by lesv** [comment] 2017-04-29 15:25
So, I tried just including the big cloud jar, no joy. :(
```
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud</artifactId>
      <version>0.17.1-alpha</version>
    </dependency>
```
[ERROR] Failed to execute goal on project flexible-pubsub: Could not resolve dependencies for project com.example.flexible:flexible-pubsub:war:1.0-SNAPSHOT: Failed to collect dependencies for com.example.flexible:flexible-pubsub:war:1.0-SNAPSHOT: Could not resolve version conflict among [com.google.cloud:google-cloud:jar:0.17.1-alpha -> com.google.cloud:google-cloud-datastore:jar:1.0.0 -> com.google.cloud.datastore:datastore-v1-protos:jar:1.3.0 -> com.google.api.grpc:grpc-google-common-protos:jar:0.1.0 -> io.grpc:grpc-all:jar:1.0.1 -> io.grpc:grpc-protobuf-nano:jar:1.0.1 -> io.grpc:grpc-core:jar:1.0.1, com.google.cloud:google-cloud:jar:0.17.1-alpha -> com.google.cloud:google-cloud-datastore:jar:1.0.0 -> com.google.cloud.datastore:datastore-v1-protos:jar:1.3.0 -> com.google.api.grpc:grpc-google-common-protos:jar:0.1.0 -> io.grpc:grpc-all:jar:1.0.1 -> io.grpc:grpc-core:jar:[1.0.1,1.0.1], com.google.cloud:google-cloud:jar:0.17.1-alpha -> com.google.cloud:google-cloud-datastore:jar:1.0.0 -> com.google.cloud.datastore:datastore-v1-protos:jar:1.3.0 -> com.google.api.grpc:grpc-google-common-protos:jar:0.1.0 -> io.grpc:grpc-all:jar:1.0.1 -> io.grpc:grpc-okhttp:jar:1.0.1 -> io.grpc:grpc-core:jar:[1.0.1,1.0.1], com.google.cloud:google-cloud:jar:0.17.1-alpha -> com.google.cloud:google-cloud-errorreporting:jar:0.17.1-alpha -> com.google.cloud:google-cloud-core-grpc:jar:1.0.0 -> io.grpc:grpc-protobuf:jar:1.2.0 -> io.grpc:grpc-core:jar:1.2.0, com.google.cloud:google-cloud:jar:0.17.1-alpha -> com.google.cloud:google-cloud-errorreporting:jar:0.17.1-alpha -> com.google.cloud:google-cloud-core-grpc:jar:1.0.0 -> io.grpc:grpc-protobuf:jar:1.2.0 -> io.grpc:grpc-protobuf-lite:jar:1.2.0 -> io.grpc:grpc-core:jar:1.2.0, com.google.cloud:google-cloud:jar:0.17.1-alpha -> com.google.cloud:google-cloud-errorreporting:jar:0.17.1-alpha -> io.grpc:grpc-netty:jar:1.2.0 -> io.grpc:grpc-core:jar:[1.2.0,1.2.0], com.google.cloud:google-cloud:jar:0.17.1-alpha -> com.google.cloud:google-cloud-errorreporting:jar:0.17.1-alpha -> io.grpc:grpc-stub:jar:1.2.0 -> io.grpc:grpc-core:jar:1.2.0, com.google.cloud:google-cloud:jar:0.17.1-alpha -> com.google.cloud:google-cloud-errorreporting:jar:0.17.1-alpha -> io.grpc:grpc-auth:jar:1.2.0 -> io.grpc:grpc-core:jar:[1.2.0,1.2.0]] -> [Help 1]

**Comment by garrettjonesgoogle** [comment] 2017-04-30 04:59
So it looks like the mess is caused by com.google.cloud.datastore:datastore-v1-protos:jar:1.3.0 depending on com.google.api.grpc:grpc-google-common-protos:jar:0.1.0 . If we could advance the grpc-google-common-protos dependency to 0.1.9, everything would be sane. Maybe you could override the version on your side for the moment?

**Comment by vam-google** [comment] 2017-04-30 05:09
Adding this this to the pom.xml should help:
```
  <dependencyManagement>
    <dependencies>
      <dependency>
          <groupId>io.grpc</groupId>
          <artifactId>grpc-core</artifactId>
          <version>1.2.0</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

As Garret mentioned, this is caused by the fact that datastore transitively is dependent on grpc-google-comon-protos 0.1.0, while the whole project is using 1.2.

This problem exists only for currently released google-cloud-datastore-1.0.0 and for google-clou-0.17.1-alpha (as it depends on datastore 1.0.0). The rest of the clients should work fine. 

So complete working pom.xml may look like this (tested on my machine and it compiles fine):

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>google-cloud-workingdatastore</artifactId>
  <groupId>com.google.cloud</groupId>
  <version>0.0.1</version>
  <packaging>jar</packaging>

  <dependencyManagement>
    <dependencies>
      <dependency>
          <groupId>io.grpc</groupId>
          <artifactId>grpc-core</artifactId>
          <version>1.2.0</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-datastore</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-pubsub</artifactId>
      <version>0.17.1-alpha</version>
    </dependency>
  </dependencies>
</project>
```

**Comment by lesv** [comment] 2017-05-01 16:51
Yep - totally understand, just don't want to put that in a bunch of sample code. :(

**Comment by garrettjonesgoogle** [comment] 2017-05-04 17:55
I have filed https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/170 to get datastore-v1-protos updated.

**Comment by garrettjonesgoogle** [comment] 2017-05-04 23:08
This is fixed in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2029 . We will track the updating of datastore-v1-protos separately.

**Closed by garrettjonesgoogle** 2017-05-04 23:08 UTC
Labels: Priority: P0
