### ISSUE TITLE
Add a ChannelProvider for use with the emulator

### ISSUE THREAD

**Issue by kamalaboulhosn** [GoogleCloudPlatform/google-cloud-java#2028] opened 2017-05-02 20:01 UTC
The gcloud Pub/Sub emulator require a Channel that has negotiationType set to NegotiationType.PLAINTEXT.  That means one needs to create a ChannelProvider that returns Channels with this set. It would be useful if the client library provided the ability to set this on a ChannelProvider in the library already or a builder that could be used to generate one easily.

**Comment by pongad** [comment] 2017-05-03 03:41
Duplicate of #1973

**Closed by pongad** 2017-05-03 03:41 UTC
