### ISSUE TITLE
BigQuery: support Tables: patch

### ISSUE THREAD

**Issue by juhoautio** [GoogleCloudPlatform/google-cloud-java#1564] opened 2017-01-25 15:40 UTC
Add support for this:
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/patch

..unless it's already somehow possible to add or modify a field without specifying all the existing fields?

Internally `BigQueryImpl.update` seems to call `bigQueryRpc.patch`, but when I tried to call `BigQuery.update` with only one field (the field to be added), I got an error that the schema doesn't match with the existing one.

**Comment by tcoffee-google** [comment] 2017-06-12 17:51
To clarify, is this the method you were using? http://googlecloudplatform.github.io/google-cloud-java/0.19.0/apidocs/com/google/cloud/bigquery/Table.html#update-com.google.cloud.bigquery.BigQuery.TableOption...-

And does this method do what you want? http://googlecloudplatform.github.io/google-cloud-java/0.19.0/apidocs/com/google/cloud/bigquery/spi/v2/BigQueryRpc.html#patch-com.google.api.services.bigquery.model.Table-java.util.Map-

**Comment by juhoautio** [comment] 2017-06-12 18:30
I'm not actively working on this any more, so from my perspective this issue could be closed any way.

But is that a recently added method or was it there already on January 25th? The javadoc on `BigQueryRpc#patch` seems to match with https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/patch, so it seems to be what I was looking for back in the day.

**Comment by tcoffee-google** [comment] 2017-06-12 19:10
> Internally BigQueryImpl.update seems to call bigQueryRpc.patch, but when I tried to call BigQuery.update with only one field (the field to be added), I got an error that the schema doesn't match with the existing one.

After looking closely, this still seems odd to me. @garrettjonesgoogle before I try to reproduce it, any idea why this would be the case?

**Comment by garrettjonesgoogle** [comment] 2017-06-13 17:34
@tcoffee-google No, I haven't worked with this functionality yet.

**Comment by garrettjonesgoogle** [comment] 2017-08-11 17:08
I'm going to close this since the requester has stated they don't need it.

**Closed by garrettjonesgoogle** 2017-08-11 17:08 UTC
Labels: API: bigquery, Priority: P2+, Type: Enhancement
