### ISSUE TITLE
io.grpc.StatusRuntimeException: UNAVAILABLE: The service was unable to fulfill your request. Please try again. [code=8a75]

### ISSUE THREAD

**Issue by r-tock** [GoogleCloudPlatform/google-cloud-java#1309] opened 2016-10-04 19:55 UTC
We started seeing this issue today. Is there a service outage happening?

**Comment by mziccard** [comment] 2016-10-04 20:26
What functionality is throwing this exception? Does it happen systematically? Our integration tests run smoothly [5 hours ago](https://travis-ci.org/GoogleCloudPlatform/google-cloud-java/builds/164967760).

**Comment by r-tock** [comment] 2016-10-04 20:31
This was when creating a subscription. We are not hitting any quota limit for that just confirmed. Just started 30 mins ago.

**Comment by jjlueck-tock** [comment] 2016-10-04 21:08
One more bit of information on this. 

We receive this exception when creating a subscription to a topic that was created with the older 0.3.0 release of the Java PubSub client. The topic was created many, many months ago.

I just tried to create a new topic and then a subscription to that topic using the 0.4.0 release and I did not get this error.

**Comment by mziccard** [comment] 2016-10-04 21:15
This is very strange. I see not reason why creating a subscription for an "old" topic should fail. I would also be surprised if `google-cloud` version had something to do with this as well. Can you confirm this happens every time you try to create the subscription?

**Comment by jjlueck-tock** [comment] 2016-10-04 21:23
I can confirm, yes. Would it help to provide the project name and topic that is having the problem?

**Comment by mziccard** [comment] 2016-10-04 21:33
[The Pub/Sub google group](https://groups.google.com/forum/#!forum/cloud-pubsub-discuss) could be a better place to receive help on this.

Just to have some more information: can a subscription to that topic be created via the web console?

**Comment by jjlueck-tock** [comment] 2016-10-04 21:37
Good question.

The answer is no. This is what I received when trying to create the subscription to the topic via the webconsole.

<img width="531" alt="screen shot 2016-10-04 at 4 36 19 pm" src="https://cloud.githubusercontent.com/assets/10246163/19093413/b6a5fb80-8a50-11e6-9c69-630e54088bdb.png">

**Comment by mziccard** [comment] 2016-10-04 21:45
> The answer is no. This is what I received when trying to create the subscription to the topic via the webconsole.

This seems to rule out an issue with our library. Can you confirm you created the topic with 0.3.0? I am asking because in previous versions (<= `0.2.7`) we were using the experimental endpoint. This should have no impact but I just want to get more information.

@eschapira @kamalaboulhosn do you guys have some idea on this?

**Comment by r-tock** [comment] 2016-10-04 21:53
@mziccard We used the google client pubsub api before. Not the Google cloud java api

**Comment by r-tock** [comment] 2016-10-04 22:34
One more update Our production code which is running the old google client pubsub api is also hitting this issue. So this is a service related issue.

**Comment by mziccard** [comment] 2016-10-05 06:20
@r-tock @jjlueck-tock And you are not hitting the 10000subscriptions-per-topic limit, right? [https://groups.google.com/forum/#!topic/cloud-pubsub-discuss] is the best place for this issue, support can also help given your project id and topic name.

**Comment by jjlueck-tock** [comment] 2016-10-05 19:57
This appears to be service related. We have a support ticket going instead. You may close this issue as we're pretty sure that this is not a Java client bug.

**Comment by mziccard** [comment] 2016-10-05 21:20
>  We have a support ticket going instead.

Hope this gets fixed soon.

**Closed by mziccard** 2016-10-05 21:20 UTC
Labels: pubsub
