### ISSUE TITLE
[IoT] IoT client got Internal error HTTP/2. Received Rst Stream.

### ISSUE THREAD

**Issue by koncha99** [GoogleCloudPlatform/google-cloud-java#3367] opened 2018-06-12 03:55 UTC
Hi,

When I use the client library for IoT, I got a HTTP/2 internal error with message, "Received Rst Stream".
In here, I used listDevicesCallable() , but also got a same error for simpler call, listDevices().
Does anyone has an insight for this error?

Thank you.

### Java version
1.10

### API Version
0.51-beta (also tried 0.48-beta and 0.50-beta)

### Stacktrace
```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
Received Rst Stream
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:526)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:507)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
       ....
Caused by: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
Received Rst Stream
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:67)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:95)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:61)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1349)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:492)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:591)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more
Caused by: io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
Received Rst Stream
	at io.grpc.Status.asRuntimeException(Status.java:526)
	... 22 more

```

**Comment by hzyi-google** [comment] 2018-06-13 22:19
Hi koncha99,

I'll try to see if I can reproduce. But just wondering if you are seeing this error all the time or intermittently?

**Comment by hzyi-google** [comment] 2018-06-13 22:19
Whoops, hit the wrong button

**Comment by koncha99** [comment] 2018-06-14 04:55
Hi,
Thanks for help. It occurs all the time in my code.

**Comment by hzyi-google** [comment] 2018-06-14 17:46
Sorry I wasn't able to reproduce this issue. My code looks like:
```
DeviceManagerClient client = DeviceManagerClient.create();
RegistryName parent = RegistryName.of("[project_name]", "[zone_name]", "[registry_name]");
ListDevicesRequest request = ListDevicesRequest.newBuilder()
    .setParent(parent.toString())
    .build();
System.out.println(client.listDevices(request));
```
And the response object is successfully received. Can you share your repro code and your environment (local machine, gae/gce, etc.)?

**Comment by koncha99** [comment] 2018-06-15 06:58
Sorry, I need to modify my comment before. It occurs intermittently. 
I tried again from local machine with the code which is same with yours. 
Code: https://github.com/koncha99/cloud-iot-api-sample
Region: asia-east1

But, it sometime succeeded and sometime failed with same errors before. 
Although I suspected my network environment, but situation didn't change even when I tried from another network. So I filed an issue on support desk of google clouds. 

If there is any progress, I will inform you.

**Comment by hzyi-google** [comment] 2018-09-04 21:40
Any updates on this? I'll close this if the issue has gone.

**Closed** 2018-09-17 17:46 UTC
Labels: api: iot, priority: p2, status: blocked, type: question
