### ISSUE TITLE
Allow passing path to keyfile to use for credentials

### ISSUE THREAD

**Issue by sundewei** [GoogleCloudPlatform/google-cloud-java#2143] opened 2017-06-13 19:05 UTC
@garrettjonesgoogle
Hi,
I was informed to create a ticket for Java from an existing ticket which was for Ruby:
https://github.com/googleapis/toolkit/issues/1324

Currently I am trying to create a custom metric in Java but was not able to find out how to create the  MetricServiceClient object from the json keyfile.

If you can provide me a Java example of doing it, that'd ok for now....many thanks

Dewei

Below is my code:
Line 1
`CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(
            ServiceAccountCredentials.fromStream(new FileInputStream(gcpJsonKeyFilePath)));`
Line 2
`final MetricServiceClient client = MetricServiceClient.create((MetricServiceSettings) MetricServiceSettings.newBuilder().setCredentialsProvider(credentialsProvider).build());`

Here is the error message:

`Exception in thread "main" java.lang.IllegalStateException: Missing required properties: totalTimeout initialRetryDelay retryDelayMultiplier maxRetryDelay initialRpcTimeout rpcTimeoutMultiplier maxRpcTimeout`

**Comment by garrettjonesgoogle** [comment] 2017-06-13 20:33
Use `MetricServiceSettings.defaultBuilder()` instead of `MetricServiceSettings.newBuilder()`.

**Comment by sundewei** [comment] 2017-06-13 20:39
Thanks a lot for the input, I tried your approach:

`CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(
            ServiceAccountCredentials.fromStream(new FileInputStream(gcpJsonKeyFilePath)));`
`final MetricServiceClient client =
            MetricServiceClient.create((MetricServiceSettings) MetricServiceSettings.defaultBuilder().setCredentialsProvider(credentialsProvider).build());`

But now I got this error...any suggestion or code snippet is appreciated:
`Exception in thread "main" java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.`

**Comment by garrettjonesgoogle** [comment] 2017-06-13 20:43
Hmm that looks like it should work. @neozwu could you investigate?

**Comment by sundewei** [comment] 2017-06-13 21:19
Just FYI, the example I listed above used this dependency:


<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-monitoring</artifactId>
    <version>0.19.0-alpha</version>
</dependency>

**Comment by sundewei** [comment] 2017-06-13 21:31
I have added more info to the code, it looks like the MetricServiceSettings' defaultBuilder does not get the CredentialsProvider after my setter call:

![screen shot 2017-06-13 at 2 29 01 pm](https://user-images.githubusercontent.com/547750/27105577-f01a0734-5044-11e7-9261-997411cadd27.png)

**Comment by neozwu** [comment] 2017-06-13 22:20
@sundewei I can reproduce this error. This is due to a bug in version 0.19.0-alpha. We have a fix in our next release (through this [PR](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2116), and the code change is [here](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/MetricServiceSettings.java#L311))

**Comment by sundewei** [comment] 2017-06-14 00:30
Thanks a lot for checking it.

Please kindly let me know once you have the API which would take a keyfile InputStream like other GCP services, that's our prefer way of using it.

Dewei

**Comment by neozwu** [comment] 2017-06-16 20:08
@sundewei the new release (0.20.0-alpha) is out. I'm closing this issue now but feel free to reopen it if you still have the same problem.

**Closed by neozwu** 2017-06-16 20:08 UTC
