### ISSUE TITLE
Exception while writing to stackdriver

### ISSUE THREAD

**Issue by creativcoder** [GoogleCloudPlatform/google-cloud-java#3291] opened 2018-05-21 09:04 UTC
Version for stackdriver in build.gradle:

`compile 'com.google.cloud:google-cloud-logging:1.7.0'`

Hi our logging calls to stackdriver in our service is facing this exception since morning:

com.google.api.gax.batching.FlowController$FlowControlRuntimeException: The maximum number of batch bytes: 10485760 have been reached.

	at com.google.api.gax.batching.FlowController$FlowControlRuntimeException.fromFlowControlException(FlowController.java:55)
	at com.google.api.gax.rpc.BatchingCallable.futureCall(BatchingCallable.java:77)
	at com.google.api.gax.rpc.EntryPointUnaryCallable.futureCall(EntryPointUnaryCallable.java:70)
	at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:89)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.write(GrpcLoggingRpc.java:199)
	at com.google.cloud.logging.LoggingImpl.writeAsync(LoggingImpl.java:591)
	at com.google.cloud.logging.LoggingImpl.writeLogEntries(LoggingImpl.java:558)
	at com.google.cloud.logging.LoggingImpl.write(LoggingImpl.java:521)
	at com.google.cloud.pubsub.v1.MessageDispatcher$2.run(MessageDispatcher.java:412)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

The exception happens on `write` method on the the `Logging` type.

Any pointers to resolve this would be helpful

**Comment by andreamlin** [comment] 2018-05-21 18:55
@pongad Would you know anything about batching maximums in regards to this scenario?

**Comment by pongad** [comment] 2018-05-21 22:07
This has already been fixed in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2741. Would it be possible for you to update the dependency?

The root cause is that the application is logging more quickly than we can send the logs. Before the fix we throw an exception, now we block the application until we can keep up instead.

**Closed by pongad** 2018-05-21 22:07 UTC
Labels: api: logging, type: question
