### ISSUE TITLE
Home page on website looks screwy

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/google-cloud-java#2701] opened 2017-12-12 19:02 UTC
Something is amiss with the [home page for the google-cloud-java website](https://googlecloudplatform.github.io/google-cloud-java/0.32.0/index.html). The text "google-cloud" is overlapping with itself:

![google-cloud-java-home-page](https://user-images.githubusercontent.com/1522391/33903052-d786e176-df2b-11e7-8864-0668654702df.png)

**Comment by vchudnov-g** [comment] 2017-12-13 00:50
Duplicate of #2663

**Closed by vchudnov-g** 2017-12-13 00:50 UTC
