### ISSUE TITLE
No functional channel provider found

### ISSUE THREAD

**Issue by mamdouhweb** [GoogleCloudPlatform/google-cloud-java#2085] opened 2017-05-23 18:20 UTC
While trying to run `google-vision-api` with a Scala project I'm getting the following exception.
```code
io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact
        at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:126)
        at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:45)
        at com.google.api.gax.grpc.InstantiatingChannelProvider.createChannel(InstantiatingChannelProvider.java:129)
        at com.google.api.gax.grpc.InstantiatingChannelProvider.getChannel(InstantiatingChannelProvider.java:116)
        at com.google.api.gax.grpc.ChannelAndExecutor.create(ChannelAndExecutor.java:65)
        at com.google.api.gax.grpc.ClientSettings.getChannelAndExecutor(ClientSettings.java:77)
        at com.google.cloud.vision.spi.v1.ImageAnnotatorClient.<init>(ImageAnnotatorClient.java:120)
        at com.google.cloud.vision.spi.v1.ImageAnnotatorClient.create(ImageAnnotatorClient.java:111)
        at com.google.cloud.vision.spi.v1.ImageAnnotatorClient.create(ImageAnnotatorClient.java:102)
```

I have tried changing the grpc-netty version and the http2 dependency from netty codec version as well. I also tried excluding the library and replacing it with grpc-okhttp to no hope!

Appreciate any help here

**Comment by vam-google** [comment] 2017-05-23 21:33
Hi @mamdouhweb, please provide your project dependencies configuration (i.e. which artifacts and versions you depend on). Also, does it work if you try to do the same thing in java (i.e. is it specific to scala)?

**Comment by mamdouhweb** [comment] 2017-05-23 21:38
@vam-google thanks for the quick reply. I haven't tried it in Java, I'm assuming it works as you guys have it in the examples.
as for my dependency list:

```scala
"joda-time" % "joda-time" % versions.jodaTime
"com.typesafe.akka" %% "akka-http-core" % versions.akkaHttpCore,
      "com.typesafe.akka" %% "akka-http" % versions.akkaHttp,
      "com.typesafe.akka" %% "akka-http-testkit" % versions.akkaHttpTestKit,
      "com.typesafe.akka" %% "akka-http-spray-json" % versions.akkaHttpSprayJson,
      "com.typesafe.akka" %% "akka-http-jackson" % versions.akkaHttpJackson,
      "com.typesafe.akka" %% "akka-slf4j" % versions.akkaSlf4j,
      "com.typesafe.scala-logging" %% "scala-logging-slf4j" % versions.slf4jScalaLogging,
      "org.slf4j" % "slf4j-api" % versions.slf4jAPI,
      "org.slf4j" % "log4j-over-slf4j" % versions.slf4jLog4j,
      "ch.qos.logback" % "logback-classic" % versions.logbackClassic,
      "ch.qos.logback" % "logback-core" % versions.logbackCore,
      "com.spotify" % "async-google-pubsub-client" % versions.cloudPubSub,
      "com.google.cloud" % "google-cloud-vision" % versions.cloudVision

```

I also ran dependency tree command and I can see grpc-netty, here's a screen shot that might be helpful

<img width="1139" alt="screen shot 2017-05-23 at 5 38 07 pm" src="https://cloud.githubusercontent.com/assets/1148114/26377534/ae79b930-3fde-11e7-989a-2d9eadb097a5.png">

**Comment by mamdouhweb** [comment] 2017-05-23 21:39
Addendum:
Cloud vision version is 
```scala
val cloudVision = "0.18.0-beta"
```

**Comment by mamdouhweb** [comment] 2017-05-23 22:58
After a fight with this issue, it is fixed now!

The main cause of the issue is the horrifying combination between `io.netty.versions.properties` and `sbt assembly`

That said, this is definitely not a bug, and I apologize for taking your time @vam-google 
For anyone in the future who might face the same problem, just add the following line in your `projectAssemblySettings`

```scala
case PathList("META-INF", "io.netty.versions.properties") => MergeStrategy.rename 

// Note: using any of the following MergeStrategies (last, first or discard) will definitely cause issues, I haven't tried merge but you can definitely try it yourself :)
```

**Comment by vam-google** [comment] 2017-05-23 23:05
Good to hear that it is not a bug =). Closing the issue.

**Closed by vam-google** 2017-05-23 23:05 UTC
Labels: API: vision, Priority: P2+, Type: Bug
