### ISSUE TITLE
Fix network quota error in compute integration tests

### ISSUE THREAD

**Issue by tcoffee-google** [GoogleCloudPlatform/google-cloud-java#2118] opened 2017-06-06 16:13 UTC
Remove GCE networks from gcloud-devel project.

https://www.google.com/url?q=https%3A%2F%2Ftravis-ci.org%2FGoogleCloudPlatform%2Fgoogle-cloud-java%2Fjobs%2F239819052&sa=D&sntz=1&usg=AFQjCNHHgq88UgaiKxAPxGs8u8rW4VBFcw

**Comment by garrettjonesgoogle** [comment] 2017-06-08 15:22
There appear to be 9 networks from tests (10 total because of `default`). 

```
gcloud compute networks list | wc -l
11
```
(subtract one for the header line)

I tried deleting a network:

```gcloud compute networks delete xxxxxxx```

But it says the network is already being used by a firewall. I tried deleting the firewall:

``` gcloud compute firewall-rules delete xxxxxxx```

This succeeded, but when I went back to delete the network again, it said there was another firewall using it. I did a listing of firewall rules, and there were 79 (after I deleted two):

```
gcloud compute firewall-rules list | cut -f 1 -d ' ' | grep '^test-'  | wc -l
79
```

I think there must be an issue in our test cleanup code for compute integration tests where networks aren't getting cleaned up always because of existing firewall rules blocking the deletion of networks.

cc @neozwu

**Comment by garrettjonesgoogle** [comment] 2017-06-09 01:07
@neozwu manually cleared out networks from the console.

When rerunning integration tests, one of the runs failed with a compute error. I checked the networks in the console, and 1 new network was left around with 9 firewall rules.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.google.cloud.compute.it.ITComputeTest
Tests run: 58, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 663.527 sec <<< FAILURE! - in com.google.cloud.compute.it.ITComputeTest
testCreateNetworkAndSubnetwork(com.google.cloud.compute.it.ITComputeTest)  Time elapsed: 51.609 sec  <<< FAILURE!
java.lang.AssertionError: expected null, but was:<Network{generatedId=1683690868081708972, creationTimestamp=1496969539480, networkId=NetworkId{project=gcloud-devel, network=test-0e9d60110b4c494db45809d9-create-subnetwork-network}, description=null, configuration=SubnetNetworkConfiguration{type=SUBNET, autoCreateSubnetworks=false, subnetworks=null}}>
	at com.google.cloud.compute.it.ITComputeTest.testCreateNetworkAndSubnetwork(ITComputeTest.java:1511)
Results :
Failed tests: 
  ITComputeTest.testCreateNetworkAndSubnetwork:1511 expected null, but was:<Network{generatedId=1683690868081708972, creationTimestamp=1496969539480, networkId=NetworkId{project=gcloud-devel, network=test-0e9d60110b4c494db45809d9-create-subnetwork-network}, description=null, configuration=SubnetNetworkConfiguration{type=SUBNET, autoCreateSubnetworks=false, subnetworks=null}}>
```

**Comment by neozwu** [comment] 2017-06-16 22:00
It seems we are having more zombie networks and firewall rules piling up again

**Comment by tcoffee-google** [comment] 2017-06-16 22:15
Still investigating this one ...

**Comment by garrettjonesgoogle** [comment] 2017-07-17 21:20
This keeps gumming up our integration tests. We should either fix the problem or nuke the tests.

**Comment by tcoffee-google** [comment] 2017-07-18 21:32
It appears to me that these networks are being generated by tests for Node.js: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/compute/system-test/compute.js 

The Compute tests in Node.js use a non-standard setup to minimize resource creation, which removes previously-created objects after all tests have finished running. The idea appears to be that, even if a test run fails, the beginning of a subsequent test run will remove objects left behind. It appears that firewalls should be deleted before networks, but there doesn't seem to be any verification that the deletions are successful.

There's a consistent pattern that each network left behind has 9 associated firewall rules of the same configuration. It's not clear to me how these rules are created.

@lukesneeringer @stephenplusplus can you investigate?

**Comment by stephenplusplus** [comment] 2017-07-18 21:44
@tcoffee-google thanks for the initial investigation. The networks created by our system tests are done through the project "gcloud-node-regression-tests (ID: long-door-651)"-- how are resources from that project showing up for the Java project?

**Comment by stephenplusplus** [comment] 2017-07-18 22:06
In the Node before/after hooks, we delete all resources. One of [those functions that executes is](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/425701b9f67885763f22f1547955fbd83a754bcf/packages/compute/system-test/compute.js#L1399):

```js
  function deleteAllGcloudTestObjects(callback) {
    async.eachSeries([
      'getVMs',
      'getAddresses',
      'getAutoscalers',
      'getDisks',
      'getInstanceGroups',
      'getFirewalls',
      'getSubnetworks',
      'getHealthChecks',
      'getNetworks',
      'getRules',
      'getSnapshots',
    ], callAndDeleteGcloudTestObject, callback);
  }
```

These fire in order, so firewalls are deleted before networks. If a deletion of any of these resource types fails, the system tests will exit with an error (https://github.com/GoogleCloudPlatform/google-cloud-node/blob/425701b9f67885763f22f1547955fbd83a754bcf/packages/compute/system-test/compute.js#L1415):

```js
  function callAndDeleteGcloudTestObject(methodName, callback) {
    compute[methodName]({
      filter: 'name eq ' + TESTS_PREFIX + '.*'
    }, function(err, objects) {
      if (err) {
        callback(err);
        return;
      }

      async.each(objects, function(object, callback) {
        object.delete(compute.execAfterOperation_(callback));
      }, callback);
    });
  }
```

`callAndDeleteGcloudTestObject` first gets a list of resources that match our naming convention. The resources we create [are always named `gcloud-tests-{resource_type}-{uuid}`](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/425701b9f67885763f22f1547955fbd83a754bcf/packages/compute/system-test/compute.js#L1374). After getting them, it deletes them-- if the delete fails, the `callback` is executed with an error, and the system tests process would exit with it.

Looking at all of the places we call a delete method, they all wait for the operation returned to complete, erroring out if it wasn't successful.

Here is what the list of Firewalls for the gcloud-node-regression-tests project looks like in the Console UI (https://console.cloud.google.com/networking/firewalls/list):

![image](https://user-images.githubusercontent.com/723048/28341801-2a759e48-6be3-11e7-95e9-612189b76094.png)

The `default-` prefix leads me to believe these aren't being created by any of our tests, and they exist by default for the "default network": https://console.cloud.google.com/networking/networks/details/default -- I don't believe we created that and it doesn't appear we have a way to delete them.

Everything appears to be "clean" for the gcloud-node-regression-tests project, but let me know if I'm not looking in the right place, or missed an important clue from the research you've already done.

**Comment by tcoffee-google** [comment] 2017-07-19 03:20
I'm fairly sure that the orphaned networks in the `gapic-test` project are coming from these tests, since the particular naming pattern appears to result from the (presumably unintended) behavior of https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/compute/system-test/compute.js#L1378 , which I don't see occurring anywhere else. These show up at bottom in the list below:
![networks](https://user-images.githubusercontent.com/16905211/28349000-3ad4daee-6c0e-11e7-8488-e501ab171e19.png)

It looks like https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/system-test/env.js reads a project ID from local environment variables --- is it plausible that someone is running the integration tests with local variables set to the `gapic-test` project?

**Comment by stephenplusplus** [comment] 2017-07-19 17:27
It's definitely possible, and apparently the case, since I agree that those networks must have come from our tests.

As far as who ran them: @lukesneeringer any ideas? It's not from myself, Dave (@callmehiphop), or the system tests (AppVeyor and Circle). We don't have access to the `gapic-test` project.

As far as how it happened: if the tester aborted the process in the middle of the test run, the after hook wouldn't have run to clean them up. And if they didn't run the tests again, the before hook wouldn't have run.

As far as what now: Manually clear them (sorry), try to track down the user running them, and ask that they use another project that won't interfere with other users. If we can't identify the user, the only thing to help would be something like a Travis nightly build that deletes the `gcloud-tests-network-*` resources. Hopefully it won't get to that point.

**Comment by tcoffee-google** [comment] 2017-07-19 20:31
Since it sounds like there's not a legitimate use case for running these tests on the `gapic-test` project, I've modified our integration test setup to remove them, which I expect will avoid the recurring problem. If someone is running the Node.js integration tests on `gapic-test` while our CI build begins, this could cause their tests to fail, but that seems preferable to the present issue.

**Comment by neozwu** [comment] 2017-07-19 20:58
If you search the logging using the network-id, it should be able to tell you the service account that creates the network - that might be useful information.

**Comment by tcoffee-google** [comment] 2017-07-19 21:48
The networks I just removed must be old enough that they no longer show up in the logs.

**Comment by tcoffee-google** [comment] 2017-07-21 23:28
Still seeing some similar errors despite apparent non-existence of orphaned networks: https://www.google.com/url?q=https%3A%2F%2Ftravis-ci.org%2FGoogleCloudPlatform%2Fgoogle-cloud-java%2Fjobs%2F255764601&sa=D&sntz=1&usg=AFQjCNGYPTkzJ0WPOIccAmP18KjzK3ExwA

Also need to install `gcloud` on Travis for this script to work properly.

**Comment by garrettjonesgoogle** [comment] 2017-07-24 15:47
Installing `gcloud` seems like really high overhead when we are just using it to call cloud services... and that's what our client library is for, calling cloud services.

**Comment by tcoffee-google** [comment] 2017-07-24 18:39
I was concerned about using our library to set up tests for itself, and it seems [fairly simple](https://stackoverflow.com/a/38776394) to install `gcloud` for the Travis build. Do you think we should clean up the networks internally as part of the integration tests?

**Comment by garrettjonesgoogle** [comment] 2017-07-24 19:07
Ok - is it known how long the installation takes (since it will add that time onto every integration test run in Travis)?

**Comment by tcoffee-google** [comment] 2017-07-24 19:17
It takes ~10 sec on my local machine. The installation portion may be slower on Travis, but I'd imagine well under a minute.

**Comment by garrettjonesgoogle** [comment] 2017-07-24 19:20
Alrighty, that should be fine I think.

**Comment by neozwu** [comment] 2017-07-24 19:22
Would it be possible to 'curl' a http request to delete the networks ?

**Comment by tcoffee-google** [comment] 2017-07-25 01:02
Probably, but it's more complicated and doesn't seem to save that much overhead. As the `gcloud` solution is already tested and not too bad, I'm inclined to go with it for now. Any objections?

**Comment by tcoffee-google** [comment] 2017-07-26 18:41
I've set it up to cache the SDK to avoid a download and install unless updates are available.

**Comment by tcoffee-google** [comment] 2017-07-26 21:41
@garrettjonesgoogle noticed that these tests are running not on the `gapic-test` project, but on the `gcloud-java` project, to which I'd previously not had access. The orphan networks on this project do look to be remnants from interrupted Compute integration tests on google-cloud-java. As my #2251 already filled in the gaps I found in testing removal, I suggest the remedy should be the same.

**Comment by garrettjonesgoogle** [comment] 2017-07-27 17:15
So I looked at the test runs on the latest commit (with @tcoffee-google 's two fixes), and the gcloud commands still didn't work (project wasn't set). I tried fixing this in a PR, but then I ran against a problem with account not being set.

At this point I just decided to run the commands manually because I want to get a release out. The commands didn't work though, so I had to use a command-line for loop to delete all the firewall rules. When I then went to manually delete the networks, it gave me errors saying that there were still firewall rules. I remember @neozwu hitting this problem before, and he had to use the console at https://pantheon.corp.google.com/ to manually delete them. I have now gone and done the same.

At this point I don't really want to bother with these network tests (in the Compute integration tests) - we aren't updating the Compute code, and it's causing way too much pain to solve in the "right" way. I think we should just disable the network tests for now, and remove the gcloud commands we tried to add to the travis script.

**Comment by tcoffee-google** [comment] 2017-07-27 17:48
The debug cycle with Travis has been annoying. I'd considered trying to use [`travis-build`](https://github.com/travis-ci/travis-build) to test locally, but it didn't seem worth the trouble.

What happened when you ran the `gcloud` commands? For the other problems, it looks to me like the fix is to set the environment variables in `integration_test_env.sh` at the beginning and do `gcloud auth application-default login`.

**Comment by garrettjonesgoogle** [comment] 2017-07-27 17:53
When I ran the `gcloud` commands, it only deleted the first firewall. I think this has to do with handling of newlines in variables. That particular item is probably an easy fix, and maybe is purely due to the script using a different shell than the one I use.

You can't do `gcloud auth application-default login` remotely because that requires browser interaction.

If we replace the current google-cloud-compute with a new generated client, all of this becomes moot, which is why I'm inclined to disable the tests.

**Comment by tcoffee-google** [comment] 2017-07-27 17:59
Probably.

Yes, just realized that.

I was concerned that other resources could end up hitting quota in the same way if Compute ITs are interrupted. Were you thinking we'd just disable the network tests and see how it goes?

**Comment by garrettjonesgoogle** [comment] 2017-07-27 18:01
Yeah, just see how it goes. Other resources have had quota problems in the past, but they haven't shown up again after being fixed. The network quota seems to consistently come back, though.

**Comment by neozwu** [comment] 2017-07-27 20:57
I agree that we should delete those tests .   Regarding the issue of using `gcloud auth application-default login`,  I think gcloud can get credential from a service account key.json file, which supposedly is silent. I haven't tried it though.

**Comment by garrettjonesgoogle** [comment] 2017-07-31 17:15
This was fixed by https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2285 .

**Closed by garrettjonesgoogle** 2017-07-31 17:15 UTC
Labels: API: compute, Priority: P1, testing
