### ISSUE TITLE
unexpected behavior long timeout when rpc timeout is larger than max timeout

### ISSUE THREAD

**Issue by ropeck** [GoogleCloudPlatform/google-cloud-java#2068] opened 2017-05-18 15:20 UTC
Customer reports intermittent timeout errors which are longer than the max timeout set in the client.

As an example, test case:
a simple Java pub/sub publisher client project on GitHub using the latest pub/sub grpc library. 
There are instructions how to reproduce the delays which are longer than the configured timeouts. 

https://github.com/chili1k/pubsubgrpctest

The code will set up a pubsub sending messages every 3 seconds.  After adding network loss, the timeouts eventually show up as more than 30 seconds, but the max timeout is set to 4 seconds.

        RetrySettings retrySettings = RetrySettings.newBuilder()
                .setInitialRetryDelay(Duration.ofMillis(5))
                .setInitialRpcTimeout(Duration.ofMillis(200))
                .setRpcTimeoutMultiplier(2.0)
                .setRetryDelayMultiplier(2.0)
                .setMaxRetryDelay(Duration.ofMillis(4000))
                .setMaxRpcTimeout(Duration.ofMillis(4000))
                .setTotalTimeout(Duration.ofMillis(TOTAL_TIMEOUT))
                .build();

 Add latency
tc qdisc add dev eth0 root netem loss 80%

03:52:18.671 [pool-2-thread-6] WARN  org.acme.App - Publish failed after 40272 ms. DEADLINE_EXCEEDED
03:52:18.671 [pool-2-thread-6] WARN  org.acme.App - Publish failed after 31248 ms. DEADLINE_EXCEEDED
03:52:18.672 [pool-2-thread-6] WARN  org.acme.App - Publish failed after 34253 ms. DEADLINE_EXCEEDED
03:52:18.672 [pool-2-thread-6] WARN  org.acme.App - Publish failed after 37256 ms. DEADLINE_EXCEEDED

**Comment by garrettjonesgoogle** [comment] 2017-05-18 15:49
It looks like in your code, TOTAL_TIMEOUT is set to 11 seconds. In the case of total failure, I wouldn't expect it to take any less than 11 seconds. That said, it still shouldn't be more than 30 seconds.

**Comment by tcoffee-google** [comment] 2017-05-25 21:11
Thank you for the detailed report!

Running your example on my machine, I get substantially different [results](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1030238/output.txt): after 5 minutes with `TOTAL_TIMEOUT` set to 11 seconds, I have yet to see any timeout exceed 15 seconds.

Can you confirm that you still see the same results as before with your desired setting of `TOTAL_TIMEOUT`?

**Comment by ropeck** [comment] 2017-05-25 21:45
@tcoffee-google thank you for the follow up.

The issue is still ongoing with test environment. When you add the network loss, you should see a lot of intermittent network issues on the link overall.  If not, then the link isn't degraded enough to help see the timeout issue.

I'm a cloud support engineer tracking this case for a customer who provided the github repo with the example code.  If it's helpful, I can get contact info to talk with him directly to follow up and reproduce the error.
--Rodney

**Comment by chili1k** [comment] 2017-05-29 06:28
@tcoffee-google I'm the one who opened the case and posted the example on github. Unfortunately I also cannot seem to reproduce the problem any longer.

I've checked our production logs. The last time the timeout was breached heavily was last Wed (24 May). I suspect that Pub/Sub backend may somehow be able to cause long timeouts on the client. But this is hard to prove.

**Comment by tcoffee-google** [comment] 2017-05-30 17:58
I ran a similar test over the weekend, after shutting down other network activity on the machine, running 10 minutes each at different levels of network loss. You can see the results [here](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1039201/output.pdf), and the test source [here](https://github.com/chili1k/pubsubgrpctest/pull/1).

There's enough inconsistency that the results are difficult to interpret. However, it appears that there is a range of (high) network loss levels at which, during certain temporary periods, I see excessive timeout breaches sometimes as high as those you observed.

There's a lot showing up here that I don't understand. @garrettjonesgoogle @pongad do you have any thoughts on why we might see these temporary changes in behavior?

**Comment by garrettjonesgoogle** [comment] 2017-05-31 18:24
Neat graphs!

@tcoffee-google could you set up logging in gax to record the exact time stamps of each step of the retry algorithm (call issued, result received, delay period, etc)? (Don't commit it, just make the changes and run it.) I wonder if there is a "hole" somewhere that ignores the total timeout in a particular phase of the algorithm, but not others.

**Comment by garrettjonesgoogle** [comment] 2017-08-10 21:36
Given that there is no more activity on this issue and the actual problem seems to have gone away, I'm going to close this out.

**Closed by garrettjonesgoogle** 2017-08-10 21:36 UTC
Labels: API: pubsub, Priority: P2+
