### ISSUE TITLE
Publish does not work when credential JSON is provided

### ISSUE THREAD

**Issue by karikalankumaresan** [GoogleCloudPlatform/google-cloud-java#2426] opened 2017-09-11 13:27 UTC
The following code works fine when deployed to the app engine flexible environment and calls the relevant /push endpoint.

```
Publisher publisher = null;
try {
   publisher = Publisher.defaultBuilder(topic).build();
   ByteString data = ByteString.copyFromUtf8("my-message");
   PubsubMessage pubsubMessage = PubsubMessage.newBuilder().setData(data).build();
   ApiFuture<String> messageIdFuture = publisher.publish(pubsubMessage);
 } finally {
   if (publisher != null) {
     publisher.shutdown();
  }
}             
```

However, when changed the "publisher" instantiation to the following (using the JSON), the publish code executes fine, but the /push endpoint is not called.

```
    Resource resource = new ClassPathResource("xxxx.json");
    final InputStream inputStream = resource.getInputStream();
    CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(
		    ServiceAccountCredentials.fromStream(inputStream));

    publisher = Publisher.defaultBuilder(TopicName.create("microservice-qa", "testtopic1"))
	    .setCredentialsProvider(credentialsProvider)
	    .build();

```
Any idea on why this is the case?

**Comment by shinfan** [comment] 2017-09-14 17:44
@neozwu Looks like an issue running on GAE. Can you take a look?

**Comment by lesv** [comment] 2017-09-20 22:40
GAE Flex

**Comment by pongad** [comment] 2018-01-18 00:40
I verified that this works as intended as of latest release.

The `publish` method returns `Future<String>` without actually waiting for the message to be published. You can try calling `publish(pubsubMessage).get()` which will wait for the message to be published and return the message ID or throws an exception explaining why the message cannot be published. That should give us more information to go with. Perhaps your service account doesn't have the right permissions etc.

Due to age of this issue, I'll close it for now. Please reopen if required.

**Closed by pongad** 2018-01-18 00:40 UTC
Labels: api: pubsub, priority: p1, release blocking, triaged for GA, type: bug
