### ISSUE TITLE
DEADLINE_EXCEEDED when using pubsub 0.13.0-alpha

### ISSUE THREAD

**Issue by autodidacticon** [GoogleCloudPlatform/google-cloud-java#1923] opened 2017-04-15 09:54 UTC
Most but not all requests made via the 0.13.0-alpha client are throwing a DEADLINE_EXCEEDED exception. Ive set log levels to FINE yet have no logging outside of the exceptions themselves. On startup my application shows the following warning:

```
io.grpc.Context: Storage override doesn't exist. Using default.
java.lang.ClassNotFoundException: io.grpc.override.ContextStorageOverride
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
```

However from cursory reading this appears normal.

Im using:

 "com.google.cloud" % "google-cloud-pubsub" % "0.13.0-alpha"
      "com.google.guava" % "guava" % "19.0"
      "com.google.api" % "gax" % "0.10.0"

My current test code is sending fixed size messages of 3894 bytes. When I attempt to use any batch settings beyond the defaults of 1000Bytes, 100messages, 1 ms, all messages are rejected with DEADLINE_EXCEEDED.

When using the default BatchingSettings from Publisher.defaultBuilder, ~90% of messages are rejected though some do succeed.

```

package com.google.cloud.examples.pubsub.snippets

import com.google.api.gax.core.ApiFuture
import com.google.cloud.pubsub.spi.v1.Publisher

import com.google.protobuf.ByteString
import com.google.pubsub.v1.PubsubMessage
import com.google.pubsub.v1.TopicName
import java.util.ArrayList
import java.util.Arrays
import java.util.List
import java.util.logging.{Level, Logger}

import com.google.api.gax.bundling.BundlingSettings
import org.joda.time.Duration

/**
  * A snippet for Google Cloud Pub/Sub showing how to create a Pub/Sub topic and asynchronously
  * publish messages to it.
  */
object CreateTopicAndPublishMessages extends App {
    val topic = TopicName.newBuilder().setProject("my-application").setTopic("my-development-topic").build()

  Logger.getLogger("").setLevel(Level.FINE)
  val batchSettings = BundlingSettings.newBuilder
    .setIsEnabled(true)
    .setDelayThreshold(Duration.standardSeconds(1))
    .setRequestByteThreshold(Publisher.getApiMaxRequestBytes)
    .setElementCountThreshold(250L)
    .build()

      val publisher = Publisher.newBuilder(topic).setBundlingSettings(batchSettings).build()
  val msg = """ /// LARGE MESSAGE """
      val messages = Seq("first message", "second message")

      val futures =
        (0 to 2000).map { message =>
          val data = ByteString.copyFromUtf8(msg.toString)
          val pubsubMessage = PubsubMessage.newBuilder().setData(data).build()
          val messageIdFuture = publisher.publish(pubsubMessage)
          messageIdFuture
        }

      futures.foreach{ messageId =>
        System.out.println("published with message ID: " + messageId.get())
      }

}

**Comment by autodidacticon** [comment] 2017-04-17 16:02
@garrettjonesgoogle this may very well have been caused by poor connectivity. I am unable to reproduce these errors from a more performant internet connection (ie work vs home).

**Comment by Mistic92** [comment] 2017-04-17 18:19
Whatever I do I get DEADLINE_EXCEEDED exception. I thought its problem with Spring and Datastore but it happens at clear project with example code from pubsub github

```
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
	at io.grpc.Status.asRuntimeException(Status.java:540)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:439)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

When running with spring I get much more errors. (it's wrapped with rxjava)

```
2017-04-17 19:53:31.099  WARN 7108 --- [pool-7-thread-1] c.b.b.v.s.impl.GoogleCloudVisionService  : Expected the service to be RUNNING, but the service has FAILED
io.reactivex.exceptions.UndeliverableException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onError(FlowableCreate.java:451)
	at com.XXX.XXX.vision.service.impl.GoogleCloudVisionService$1.failed(GoogleCloudVisionService.java:62)
	at com.google.api.gax.core.AbstractApiService$1.failed(AbstractApiService.java:68)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:509)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:507)
	at com.google.common.util.concurrent.ListenerCallQueue.run(ListenerCallQueue.java:118)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.ListenerCallQueue.execute(ListenerCallQueue.java:86)
	at com.google.common.util.concurrent.AbstractService.executeListeners(AbstractService.java:458)
	at com.google.common.util.concurrent.AbstractService.notifyFailed(AbstractService.java:407)
	at com.google.api.gax.core.AbstractApiService$InnerService.innerNotifyFailed(AbstractApiService.java:164)
	at com.google.api.gax.core.AbstractApiService$InnerService.access$400(AbstractApiService.java:144)
	at com.google.api.gax.core.AbstractApiService.notifyFailed(AbstractApiService.java:141)
	at com.google.cloud.pubsub.spi.v1.Subscriber.access$1000(Subscriber.java:76)
	at com.google.cloud.pubsub.spi.v1.Subscriber$5.failed(Subscriber.java:343)
	at com.google.api.gax.core.AbstractApiService$1.failed(AbstractApiService.java:68)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:509)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:507)
	at com.google.common.util.concurrent.ListenerCallQueue.run(ListenerCallQueue.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
	at io.grpc.Status.asRuntimeException(Status.java:540)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:439)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	... 7 more
Exception in thread "pool-10-thread-447" io.reactivex.exceptions.UndeliverableException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onError(FlowableCreate.java:451)
	at com.XXX.XXX.vision.service.impl.GoogleCloudVisionService$1.failed(GoogleCloudVisionService.java:62)
	at com.google.api.gax.core.AbstractApiService$1.failed(AbstractApiService.java:68)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:509)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:507)
	at com.google.common.util.concurrent.ListenerCallQueue.run(ListenerCallQueue.java:118)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.ListenerCallQueue.execute(ListenerCallQueue.java:86)
	at com.google.common.util.concurrent.AbstractService.executeListeners(AbstractService.java:458)
	at com.google.common.util.concurrent.AbstractService.notifyFailed(AbstractService.java:407)
	at com.google.api.gax.core.AbstractApiService$InnerService.innerNotifyFailed(AbstractApiService.java:164)
	at com.google.api.gax.core.AbstractApiService$InnerService.access$400(AbstractApiService.java:144)
	at com.google.api.gax.core.AbstractApiService.notifyFailed(AbstractApiService.java:141)
	at com.google.cloud.pubsub.spi.v1.Subscriber.access$1000(Subscriber.java:76)
	at com.google.cloud.pubsub.spi.v1.Subscriber$5.failed(Subscriber.java:343)
	at com.google.api.gax.core.AbstractApiService$1.failed(AbstractApiService.java:68)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:509)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:507)
	at com.google.common.util.concurrent.ListenerCallQueue.run(ListenerCallQueue.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
	at io.grpc.Status.asRuntimeException(Status.java:540)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:439)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	... 7 more```

**Comment by autodidacticon** [comment] 2017-04-18 13:23
This bit came up when I attempted to run my application in kubernetes on GCE:

```
Apr 18, 2017 8:17:14 AM io.grpc.internal.ChannelExecutor drain
WARNING: Runnable threw exception in ChannelExecutor
java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:174)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:151)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:139)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:109)
	at io.grpc.netty.NettyChannelBuilder.createProtocolNegotiatorByType(NettyChannelBuilder.java:335)
	at io.grpc.netty.NettyChannelBuilder.createProtocolNegotiator(NettyChannelBuilder.java:308)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DynamicNettyTransportParams.getProtocolNegotiator(NettyChannelBuilder.java:499)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.newClientTransport(NettyChannelBuilder.java:448)
	at io.grpc.internal.CallCredentialsApplyingTransportFactory.newClientTransport(CallCredentialsApplyingTransportFactory.java:61)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:209)
	at io.grpc.internal.InternalSubchannel.obtainActiveTransport(InternalSubchannel.java:186)
	at io.grpc.internal.ManagedChannelImpl$SubchannelImplImpl.obtainActiveTransport(ManagedChannelImpl.java:806)
	at io.grpc.internal.GrpcUtil.getTransportFromPickResult(GrpcUtil.java:568)
	at io.grpc.internal.DelayedClientTransport.reprocess(DelayedClientTransport.java:296)
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl$5.run(ManagedChannelImpl.java:724)
	at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:87)
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.runSerialized(ManagedChannelImpl.java:715)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl.onUpdate(ManagedChannelImpl.java:752)
	at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:174)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Would this indicate a failure to properly negotiate SSL?

**Comment by garrettjonesgoogle** [comment] 2017-04-18 14:29
@autodidacticon , that indicates that your tcnative dependency doesn't match the grpc version. Could you list all of your dependencies and versions?

**Comment by autodidacticon** [comment] 2017-04-18 15:47
@garrettjonesgoogle thanks; there was an older version tcnative in my cache (fork19) alongside the current version that seemed to have been polluting my classpath.

**Comment by autodidacticon** [comment] 2017-04-18 20:46
For those experienceing similar issues, I still get a lot of DEADLINE_EXCEEDED errors that seem to be related to connectivity between application and the pubsub endpoints. I've managed to ameliorate most of these with increased values in RetrySettings:

```
      val retrySettings = RetrySettings.newBuilder
        .setTotalTimeout(Duration.standardSeconds(30))
        .setInitialRetryDelay(Duration.millis(10))
        .setRetryDelayMultiplier(2)
        .setMaxRetryDelay(Duration.millis(Long.MaxValue))
        .setInitialRpcTimeout(Duration.standardSeconds(10))
        .setRpcTimeoutMultiplier(2)
        .setMaxRpcTimeout(Duration.standardSeconds(10))
        .build
```

**Comment by shinfan** [comment] 2017-05-08 21:26
Closing this issue since it is caused by poor connectivity.

**Closed by shinfan** 2017-05-08 21:26 UTC
Labels: API: pubsub
