### ISSUE TITLE
Cloud Java APIs should work with a local Cloud SDK with GAE Standard.

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/google-cloud-java#1500] opened 2017-01-05 00:59 UTC
With the following code in my Java Servlet:

       Storage storage = StorageOptions.getDefaultInstance().getService();
       
       
        String bucketName = "rdayalcloudtest"; // Change this to something unique
        Bucket bucket = storage.create(BucketInfo.of(bucketName));

        // Upload a blob to the newly created bucket
        BlobId blobId = BlobId.of(bucketName, "my_blob_name");
        Blob blob = bucket.create(
            "my_blob_name " + request.hashCode(), "a simple blob".getBytes(UTF_8), "text/plain");

I receive the following exception when attempting to test the code locally, using DevAppServer2:

Problem accessing /hello. Reason:

    access denied ("java.io.FilePermission" "/Users/ludo/.config/gcloud/active_config" "read")
Caused by:

java.security.AccessControlException: access denied ("java.io.FilePermission" "/Users/ludo/.config/gcloud/active_config" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at com.google.appengine.tools.development.devappserver2.DevAppServer2Factory$CustomSecurityManager.checkPermission(DevAppServer2Factory.java:232)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.FileInputStream.<init>(FileInputStream.java:127)
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:125)
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:115)
        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:420)
        at com.google.common.io.CharSource.openBufferedStream(CharSource.java:91)
        at com.google.common.io.CharSource.readFirstLine(CharSource.java:168)
        at com.google.common.io.Files.readFirstLine(Files.java:513)
        at com.google.cloud.ServiceOptions.activeGoogleCloudConfig(ServiceOptions.java:354)
        at com.google.cloud.ServiceOptions.googleCloudProjectId(ServiceOptions.java:372)
        at com.google.cloud.ServiceOptions.getDefaultProject(ServiceOptions.java:348)
        at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:281)
        at com.google.cloud.HttpServiceOptions.<init>(HttpServiceOptions.java:179)
        at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:69)
        at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:27)
        at com.google.cloud.storage.StorageOptions$Builder.build(StorageOptions.java:64)
        at com.google.cloud.storage.StorageOptions.getDefaultInstance(StorageOptions.java:99)
        at com.example.HelloAppEngine.doGet(HelloAppEngine.java:40)

**Comment by lesv** [comment] 2017-01-10 17:46
Is this the right place to report this?  I think this is an issue with the Java SDK.

**Comment by roku6185** [comment] 2017-01-12 15:17
I'm having the same problem after updating our maven plugin to:

```
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>appengine-maven-plugin</artifactId>
  <version>1.0.0</version>
</plugin>
```

I also filed a ticket in the Google Cloud Support Center.

**Comment by roku6185** [comment] 2017-01-12 15:41
I solved it by renaming the gcloud directory:

`$ mv ~/.config/gcloud ~/.config/gcloud_backup`

When I started my java service after this fix everything worked okay.

**Comment by ludoch** [comment] 2017-01-12 16:58
Les: GAE standard current sandbox rules (for Java7, lifted on Java8) does not allow a web application to read local file...
The Cloud Java library if running locally should find a way to get the metadata info it needs (project ID, project version etc) in another way than reading local file... (env var, syst prop, GAE API,...)

**Comment by lesv** [comment] 2017-01-12 22:52
@GoogleCloudPlatform/cloud-tools-for-java FYI - indirectly affects you.

@ludoch Try adding:
```xml 
   <dependency>
      <groupId>com.google.api-client</groupId>
      <artifactId>google-api-client-appengine</artifactId>
      <version>1.21.0</version>
    </dependency>
```

@garrettjonesgoogle @anthmgoogle We need to do this right for GAE Standard as we get gRPC working there.

**Comment by garrettjonesgoogle** [comment] 2017-01-13 22:53
Based on the code flow in https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L336 , if the app engine project id is found in `appEngineProjectId()`, then `googleCloudProjectId()` won't be called. Thus, something is going wrong with detecting that this is an app engine use case.

**Comment by ludoch** [comment] 2017-01-14 00:01
Maybe this logic has been testing in prod but not in the local GAE Java SDK?
Maybe, by making the project id optional in appengine-web.xml the local dev
server does not know anymore the project name to use?  This might be yet
another side effect of changing config in appengine-web.xml?

**Comment by ludoch** [comment] 2017-03-08 06:03
Customer is now escalating the issue with Google support.

**Comment by shinfan** [comment] 2017-03-09 00:22
Update: I was able to reproduce this issue with my own GAE app. Will investigate.

**Comment by shinfan** [comment] 2017-03-09 23:53
@lesv It looks like that the reflection method raises `ClassNotFound` exception [here](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L387) while running with GAE dev server. Do you know who should I talk to regading this issue?

**Comment by lesv** [comment] 2017-03-10 00:05
@garrettjonesgoogle Is probably the right person.

**Comment by Orbyt** [comment] 2017-03-10 16:23
I have run into an `AccessControlException` as well when trying to use `google-cloud-java` to access Cloud Storage.

As specified [here](https://github.com/GoogleCloudPlatform/google-cloud-java#authentication), after executing `gcloud auth application-default login` the path to the `/Users/example/.config/gcloud/application_default_credentials.json` is returned. Running my App Engine application locally after executing the above command still produces an `AccessControlException`.

Additionally, manually calling `.setCredentials()`, such as:

```
Storage storage = StorageOptions.newBuilder()
            .setCredentials(ServiceAccountCredentials.fromStream(new FileInputStream("/Users/example/.config/gcloud/application_default_credentials.json")))
            .build()
            .getService();
```
also does not work, and produces the same `AccessControlException`.

So given that other users are having a similar issue, should I assume this is not an issue with my own code? Or am I doing something incorrectly here?

**Comment by Orbyt** [comment] 2017-03-10 16:36
Continuing from my above comment, I have now also tried setting a `GOOGLE_APPLICATION_CREDENTIALS` to the path returned from `gcloud auth application-default login`, however the same `AccessControlException` is thrown.

**Comment by ludoch** [comment] 2017-03-10 18:52
What I could try to do is enable read permission so for ~/.config only in the devappserver.

**Comment by lesv** [comment] 2017-03-10 18:53
Garrett told me last night that Shin had gotten further, so I didn't look at this again.

@Orbyt You should rarely need to use `setCredentials()` -- typically it's used for x-project access, a limited scope service account, or to use from a non-google datacenter. For most other cases defaultAuth should work.  In your case, passing the credentials created by `gcloud` is incorrect - you need to pass credentials obtained from https://console.cloud.google.com -- why don't you create a new issue, and mention me in it and I'll help you out.

**Comment by shinfan** [comment] 2017-03-10 21:03
@Orbyt @ludoch

`appEngineProjectId()` uses reflection to retrieve the project ID of GAE application, the access control exception is misleading since `googleCloudProjectId()` should not be called under GAE environment.

Adding the following dependency to my application solves this issue:
```xml
<!-- https://mvnrepository.com/artifact/com.google.appengine/appengine-java-sdk -->
<dependency>
    <groupId>com.google.appengine</groupId>
    <artifactId>appengine-java-sdk</artifactId>
    <version>1.9.50</version>
</dependency>
```

**Comment by ludoch** [comment] 2017-03-10 23:33
There is no such artifact appengine-java-sdk... What did you really add?

**Comment by shinfan** [comment] 2017-03-10 23:34
@ludoch This is what I added to my pom file:
https://mvnrepository.com/artifact/com.google.appengine/appengine-api-1.0-sdk/1.9.50

**Comment by ludoch** [comment] 2017-03-10 23:40
Ok, so yes, you add the GAE Standard APIs, that define the APIs that
gcloud-java is calling via introspection, so it make sense...

So you are not accessing ~/.config/gcloud with this dep?

**Comment by shinfan** [comment] 2017-03-10 23:46
No, we should not need to access the gcloud config. According to the code flow, `getAppEngineProjectId()` should be able find the correct project ID through standard GAE API.

**Comment by Orbyt** [comment] 2017-03-10 23:54
@shinfan That dependency is already added by default when using the Java GAE quickstart.

It does not solve this issue.

**Comment by shinfan** [comment] 2017-03-13 18:56
Customer confirmed that the issue has been solved on his end. Closing this issue now.

**Closed** 2017-03-13 18:56 UTC
Labels: API: storage, running on app engine, Status: Release Blocking

**Comment by rdayal** [comment] 2017-03-27 19:52
@shinfan how come we closed this? What's the actual fix?

**Comment by shinfan** [comment] 2017-03-27 19:58
@rdayal There is nothing to fix from our side. The issue was caused by a missing dependency and the customer has confirmed things now working. See https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1731

**Comment by rdayal** [comment] 2017-03-27 20:10
Thanks, the reason this had been filed on this side is that I had run into this issue independently, and filed an internal bug about it. I wasn't following the other thread. I'll mark the other bug as closed.
