### ISSUE TITLE
pubsub: machine runs out of memory and crashes

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/google-cloud-java#3056] opened 2018-03-18 00:13 UTC
Hello! I'm running a simple pubsub consumer. This consumer receives a message, waits 5 seconds, and then acks the message. Running this consumer against a subscription with ~600,000 messages causes my app to repeatedly crash as it runs out of memory. This is running on GKE with no special configuration. I'm also using the java config defaults where possible. Possibly worth noting is that I do not see any warning/error logs related to these restarts.

Is this expected? What can be done to prevent this?

## Screenshots

![screen shot 2018-03-17 at 5 07 41 pm](https://user-images.githubusercontent.com/3584893/37561214-294c7b04-2a06-11e8-86ca-97842495e9e4.png)

![screen shot 2018-03-17 at 5 11 10 pm](https://user-images.githubusercontent.com/3584893/37561216-38eb43ce-2a06-11e8-99d1-6620386c0adb.png)

## Repro

- [Main.java](https://gist.github.com/jadekler/45a693a94cef09088f7ac592b252fde1)
- [MyReceiver.java](https://gist.github.com/jadekler/fb327281ec2d65d34b86c0cc14449838)

**Comment by jadekler** [comment] 2018-03-18 00:26
Just to add to this - this seems to be under load conditions only. I'm unable at the moment to reproduce that load, so I can't double check these results. Towards the end of next week I may be able to reproduce that load, in which case I'll update this issue (if it hasn't been updated / resolved by then).

**Comment by jadekler** [comment] 2018-03-18 00:46
I was able to repro the load and the crashing happened again. The counter in this screenshot is not the same counter as before (I removed the deployment entirely and made a brand new one, restarting the counter at 0):

![screen shot 2018-03-17 at 5 44 18 pm](https://user-images.githubusercontent.com/3584893/37561400-f39a3122-2a0a-11e8-921d-320e802b00f4.png)

Note the dips in CPU to 0.

Here are the associated "load" logs:

![screen shot 2018-03-17 at 5 45 38 pm](https://user-images.githubusercontent.com/3584893/37561406-0d69f09c-2a0b-11e8-9c5c-6f96d6444cd3.png)

**Comment by pongad** [comment] 2018-03-19 00:57
I figured out the problem. By default, the Java client caps the amount of "pending bytes". In my testing, each messages are small, so there were probably millions of messages in flight at a given time.

Now, the problem is that `receiveMessage` creates a new `Timer`. Each instance of `Timer` creates a new thread. So you were creating millions of threads on the machine. On my machine, I wasn't even able to call `ps` to get how much memory the Java process was consuming; the kernel was so busy it couldn't create a new process!

The fix: Create only one `Timer` for `MyReceiver` instance, then use it every time.

**Comment by jadekler** [comment] 2018-03-19 12:37
Doh - thanks @pongad, testing now

**Comment by jadekler** [comment] 2018-03-21 05:37
Hi @pongad - I've refactored out the creation of `Timer` (see [updated gist](https://gist.github.com/jadekler/fb327281ec2d65d34b86c0cc14449838)) and am unfortunately still running into issues:

<img width="1377" alt="screen shot 2018-03-20 at 10 32 49 pm" src="https://user-images.githubusercontent.com/3584893/37695788-1058c8f6-2c8f-11e8-8fbe-b81979af6449.png">

<img width="1583" alt="screen shot 2018-03-20 at 10 32 57 pm" src="https://user-images.githubusercontent.com/3584893/37695790-16ada7e4-2c8f-11e8-8d61-fb74c0e37015.png">

Especially worrying is `E  SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.` and `E java.lang.OutOfMemoryError: Java heap space`.

Any ideas on what's going on, or what else I can fix? Or do you reckon this is a library issue?

**Comment by pongad** [comment] 2018-03-23 01:05
Hmm.....

Could you add
```java
subscriberBuilder.setFlowControlSettings(FlowControlSettings.newBuilder().setMaxOutstandingElementCount(100L).build())
```
?

The default sets the max pending bytes to be a percentage of available memory. I might be possible that the subscriber somehow thinks it has much more memory than it does.

If this doesn't help, I think this is a problem with gRPC or Kubernetes and we should ask them for help.

**Comment by jadekler** [comment] 2018-03-23 11:38
Hey @pongad - I've tried your suggestion. This removes the errors which is 👍 , but the ingestion is quite weird:

<img width="1384" alt="screen shot 2018-03-23 at 1 33 06 pm" src="https://user-images.githubusercontent.com/3584893/37827172-13a66fce-2e9f-11e8-983f-e3072220c991.png">

As you can see, every 30 minutes it stops receiving messages for ~20m. I know that streams are indeed cancelled every 30m, but I would expect the reconnect to happen almost immediately as it does in Go.

So the two takeaways here are:

- What's up with this 20m not-receiving-messages problem?
- Is there something up in GKE that makes Java think it has more memory than it does?

**Comment by pongad** [comment] 2018-03-27 06:47
> What's up with this 20m not-receiving-messages problem?

I think this is the same problem I sent you an email about. Let's discuss there first.

> Is there something up in GKE that makes Java think it has more memory than it does?

I'm not totally sure. The `Subscriber` class uses [`Runtime::maxMemory`](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#maxMemory()). Could it be that GKE creates the JVM will a lot more memory than it's prepared to give?

Sorry to keep giving work to you, would it be possible make your instance log what `maxMomory` returns?

**Comment by jadekler** [comment] 2018-04-02 16:43
Hey @pongad, I get `940703744`. Assuming that's bytes, I think that's about 1gb. What do you reckon is going on here - why is the program going above 1gb in memory?

**Comment by jadekler** [comment] 2018-04-10 23:51
ping @pongad - is this release blocking?

**Comment by pongad** [comment] 2018-04-11 00:48
Sorry I lost track of this. I think the fix is easy enough that we might as well consider it release blocking.

**Comment by pongad** [comment] 2018-04-12 19:56
This should have been fixed by https://github.com/GoogleCloudPlatform/google-cloud-java/pull/3147

**Closed by pongad** 2018-04-12 19:56 UTC
Labels: api: pubsub, release blocking, type: feature request
