### ISSUE TITLE
Include stack trace in logged text

### ISSUE THREAD

**Issue by HunterSherms** [GoogleCloudPlatform/google-cloud-java#2587] opened 2017-11-07 16:42 UTC
I would like to include the stack trace from ERROR level logs in my logs sent back to StackDriver. How would I implement this?

**Comment by anthmgoogle** [comment] 2017-11-08 21:10
@lesv @saicheems can you answer whether there is a way to do this currently. If new functionality is required, please convert to type: feature request.

**Comment by lesv** [comment] 2017-11-18 19:42
It should do this now if you are using one of our adapters.  @jabubake Should be able to elaborate as I'm OoO til Dec.

**Comment by int08h** [comment] 2018-01-06 02:23
See also #2735

**Comment by pongad** [comment] 2018-01-19 00:17
I believe this is duplicate of #2735 like @int08h said. IIUC, the "standard" google-cloud-logging does not have this issue. I'll close as duplicate, but please reopen if I misunderstand.

**Closed by pongad** 2018-01-19 00:17 UTC
Labels: api: logging, type: question
