### ISSUE TITLE
Pipeline throws exceptions on Data Flow indicating bad linking with existing class 

### ISSUE THREAD

**Issue by AraujoArquivei** [GoogleCloudPlatform/google-cloud-java#2737] opened 2017-12-29 13:47 UTC
I'm having a similar problem to https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2496

My pipeline presets problems on executing queries. Which is done based in a class of mine. Basically, he initiates, but can't proceed.

[Exception.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1597566/Exception.txt)

this is my pom.xml:

[pom.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1597554/pom.txt)

and, finally, my class:

[BigQueryConnectionBuilder_java.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1597557/BigQueryConnectionBuilder_java.txt)

**Comment by neozwu** [comment] 2018-01-03 21:18
Looks like the issue is related to GAX. @garrettjonesgoogle @vam-google @pongad can you help take a look and/or triage this ?

**Comment by pongad** [comment] 2018-01-04 03:29
It looks like the problem is that Apache Beam depends on google-cloud-core v1.0.2, but BigQuery v0.32 requires a newer version. Could you try delcaring dependency on
```
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-core</artifactId>
    <version>1.2.0</version>
</dependency>
```
?

**Comment by pongad** [comment] 2018-01-10 23:30
Since this thread is quiet, I'll close this for now. Please reopen if this doesn't fix your issue.

**Closed by pongad** 2018-01-10 23:30 UTC
Labels: type: question
