### ISSUE TITLE
Latest release missing key Classes

### ISSUE THREAD

**Issue by joeltine** [GoogleCloudPlatform/google-cloud-java#2951] opened 2018-02-25 20:30 UTC
Hello, I noticed that the latest jar on the maven repo doesn't contain all of the classes used and referenced in the documentation. 

E.g., to test, d/l the jar: http://central.maven.org/maven2/com/google/cloud/google-cloud-language/1.17.0/google-cloud-language-1.17.0.jar. Extract it, and I see this:

```
~/Downloads/com/google/cloud/language$ ll -R v1
total 40
-rw-r--r--  1 j  staff    23K Feb 20 10:51 LanguageServiceClient.java
-rw-r--r--  1 j  staff   9.4K Feb 20 10:51 LanguageServiceSettings.java
-rw-r--r--  1 j  staff   1.3K Feb 20 10:51 package-info.java
drwxr-xr-x  5 j  staff   160B Feb 13 16:40 stub/

v1/stub:
total 36
-rw-r--r--  1 j  staff    12K Feb 20 10:51 GrpcLanguageServiceStub.java
-rw-r--r--  1 j  staff   3.0K Feb 20 10:51 LanguageServiceStub.java
-rw-r--r--  1 j  staff    17K Feb 20 10:51 LanguageServiceStubSettings.java
```

It's missing key classes like [Document](https://cloud.google.com/natural-language/docs/reference/rpc/google.cloud.language.v1#google.cloud.language.v1.Document).

**Comment by pongad** [comment] 2018-02-26 01:33
I believe this is working as intended. The package `google-cloud-language` only contains the client. However, it [imports](https://mvnrepository.com/artifact/com.google.cloud/google-cloud-language/1.17.0) package [`proto-google-cloud-language-v1`](https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-cloud-language-v1/1.1.0) which contains the classes like Document.

I think this should answer your question, so I'll close this for now. If you have other questions, please feel free to reopen.

**Closed by pongad** 2018-02-26 01:33 UTC
Labels: api: language, type: question
