### ISSUE TITLE
Credentials/Account is picked up on one machine but not another

### ISSUE THREAD

**Issue by ryan-williams** [GoogleCloudPlatform/google-cloud-java#2265] opened 2017-07-23 20:02 UTC
google-cloud-nio loads my credentials on one machine, but treats me as anonymous and rejects reads/writes on the other.

I must have some state set on the former but not the latter that is causing this, but I can't figure out what.

`gcloud config list` gives identical output on both:

```bash
$ gcloud config list
[compute]
zone = us-east1-b
[core]
account = <my email>
disable_usage_reporting = False
project = <my project>

Your active configuration is: [rbw]
```

Simple file to test reading a GCS path, `Test.java`:

```java
import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class Test {
    public static void main(String[] args) throws IOException {
        Path path = Paths.get(URI.create("gs://bucket/path"));
        System.out.println(Files.readAllLines(path, StandardCharsets.UTF_8).size());
    }
}
```

Compile it:

```
javac Test.java
```

Get latest google-cloud-nio release:

```bash
wget https://repo1.maven.org/maven2/com/google/cloud/google-cloud-nio/0.20.3-alpha/google-cloud-nio-0.20.3-alpha-shaded.jar
```

Run on machine A:

```bash
java -cp google-cloud-nio-0.20.3-alpha-shaded.jar:. Test
```

The correct number of lines in my file `gs://bucket/path` is printed.

Running the same thing on machine B gives:

```
$ java -cp google-cloud-nio-0.20.3-alpha-shaded.jar:. Test
Exception in thread "main" com.google.cloud.storage.StorageException: Anonymous users does not have storage.objects.get access to object bucket/path.
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:189)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:335)
	at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:191)
	at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:188)
	at shaded.cloud_nio.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:94)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:54)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:188)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:202)
	at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.fetchSize(CloudStorageReadChannel.java:234)
	at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.<init>(CloudStorageReadChannel.java:78)
	at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.create(CloudStorageReadChannel.java:68)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newReadChannel(CloudStorageFileSystemProvider.java:304)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newByteChannel(CloudStorageFileSystemProvider.java:265)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newInputStream(CloudStorageFileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at java.nio.file.Files.readAllLines(Files.java:3202)
	at Test.main(Test.java:11)
Caused by: shaded.cloud_nio.com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
{
  "code" : 401,
  "errors" : [ {
    "domain" : "global",
    "location" : "Authorization",
    "locationType" : "header",
    "message" : "Anonymous users does not have storage.objects.get access to object bucket/path.",
    "reason" : "required"
  } ],
  "message" : "Anonymous users does not have storage.objects.get access to object bucket/path."
}
	at shaded.cloud_nio.com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at shaded.cloud_nio.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:333)
	... 19 more
```

AFAICT, I am authed with the `gcloud` CLI the same way on both machines, per the output of `gcloud config list` above.

What else can I look at to explain why I am treated as an "anonymous user" on machine B?

**Comment by tcoffee-google** [comment] 2017-07-27 21:41
@ryan-williams just to rule it out, are there any differences in your environment variable settings such as `GCLOUD_PROJECT` or `GOOGLE_APPLICATION_CREDENTIALS`?

**Comment by ryan-williams** [comment] 2017-07-30 15:33
@tcoffee-google both of those env vars are empty on both machines :-\ thanks for having a look!

**Comment by tcoffee-google** [comment] 2017-08-01 21:05
As I'm away, I'll pass this off to @neozwu who's handling new issues this week.

**Comment by neozwu** [comment] 2017-08-02 16:59
@ryan-williams, can you try "gcloud init" to refresh the configs/credentials ?

**Comment by garrettjonesgoogle** [comment] 2017-08-10 20:57
The requester hasn't responded in a week, and the last correspondence implies the issue is fixed for them. Closing this out; please re-open if I interpreted incorrectly.

**Closed by garrettjonesgoogle** 2017-08-10 20:57 UTC
Labels: auth, Priority: P2+, Type: Question
