### ISSUE TITLE
PubSub : Internal Error while creating subscription

### ISSUE THREAD

**Issue by talonx** [GoogleCloudPlatform/google-cloud-java#3135] opened 2018-04-09 04:53 UTC
I keep getting this intermittently while creating subscriptions
```
Caused by: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0]
at com.google.api.gax.grpc.GrpcApiExceptionFactory.createException(GrpcApiExceptionFactory.java:88)
at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:112)
at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:53)
at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:458)
at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:433)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:61)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:504)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:425)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:536)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102)
```

The code is as follows (exception handling etc omitted)

```
SubscriptionName sName = SubscriptionName.create(projectId, finalSubName);
SubscriptionAdminClient subscriptionAdminClient = SubscriptionAdminClient.create()
subscriptionAdminClient.createSubscription(sName, topicName, PushConfig.getDefaultInstance(), 10 * 60)
```
I am using pull subscribers.

PubSub library version in use is 0.26.0-beta . I am unable to try this with a newer version of pubsub due to dependency conflicts with the bigtable-hbase-1.x library which is used in the same application.

**Comment by pongad** [comment] 2018-04-10 18:52
@talonx Are you still running into the issue? This exception indicates that we received a failure response from the server. If you still see this problem, I'll loop in the server team.

**Comment by talonx** [comment] 2018-04-11 06:44
@pongad It's happened once in the past week, haven't seen it since. I'll update this ticket if it happens again. If it helps, the last timestamp when it happened is 2018-04-06 13:24:56 UTC.

**Comment by pongad** [comment] 2018-05-08 00:34
@talonx Since it's unlikely that this is caused by the client lib, I'll close this for now. Please let us know if you're still seeing this problem.

**Closed by pongad** 2018-05-08 00:34 UTC
Labels: api: pubsub, type: question

**Comment by stevedj** [comment] 2021-08-03 23:11
Hi @pongad 

I got the same error,
gRPC Error (code: 13, codeName: INTERNAL, message: A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0], details: [], rawResponse: null)
(I have checked the error code but I still don't understand)

But I am using dart,

Just a bit of information , these are several values before the grpc send a request :
compressionCodec = null
credentials.isSecure=true
_transportConnector.authority= pubsub.googleapis.com
path=/google.pubsub.v1.Subscriber/StreamingPull
timeout=null
metadata= {authorization: Bearer ....
options.userAgent=dart-grpc/2.0.0
supportedEncodings = null

Just wondering if there is a solution?

Thanks
