### ISSUE TITLE
io.grpc.StatusRuntimeException: UNAVAILABLE is happening after some time

### ISSUE THREAD

**Issue by lukasz-szewc** [GoogleCloudPlatform/google-cloud-java#2502] opened 2017-10-10 14:41 UTC
I have expected strange behavior of pubsub client application. App is running and after some time it is producing (out of nowhere) following exception:

<pre>

2017-10-06 08:23:58 [pool-6-thread-9] WARN  c.g.c.p.v.StreamingSubscriberConnection - Terminated streaming with exception
io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:385)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:61)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:504)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:425)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:536)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 common frames omitted
</pre>

We are using google-cloud-pubsub library version : 0.24.0-beta

I would like to ask what is causing such particular exception, and whether or not this is a bug?

**Comment by lukasz-szewc** [comment] 2017-10-10 16:20
If that is timeout related issue, and we can configure that - please provide advices how to deal with it.

**Comment by AgentME** [comment] 2017-10-10 20:51
I have a simple application listening on pubsub running in GKE on the same google-cloud-pubsub version, and I've been getting the same stacktrace 4 times in quick bursts regularly every 2 hours.

Additionally, for me it seems like during or shortly after these exception bursts is the only time the application receives pubsub messages. Pubsub messages queue for hours until one of these exception bursts happen. [example log](https://gist.github.com/AgentME/52afd5c953a5f67fe344a8a6f0585f68). (Maybe related: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2501)

**Comment by dkushner** [comment] 2017-10-11 03:26
We are experiencing the exact same behaviour as @AgentME mentions. I see in another ticket that a support ticket was opened up with GCP, has there been an update?

**Comment by lukasz-szewc** [comment] 2017-10-12 09:40
@AgentME  is right , exactly the same behavior I am experiencing. Application is in the state when there are no messages to consume. Exception like above happens regularly every 2 hour and it is followed by this:  

<pre>
DEBUG c.g.c.p.v.StreamingSubscriberConnection - Initializing stream to subscription projects/kohls-ocf-lle/subscriptions/ocf-oic-dev027-safetystock-inbound-sub with deadline 10
</pre>

It seems like it is "re-initialization" of connection. When that happens - application starts to consume messages that were already available for consumption.

After successful consumption - timeout period is going to be extended. Next timeout will happen - 2 hours from last successful consumption.

It is definitely related to #2501

**Comment by danieln100** [comment] 2017-10-20 14:43
We are experiencing the same problem.

**Comment by danieln100** [comment] 2017-10-24 15:15
@lukasz-szewc Were you able to find a solution?

**Comment by lukasz-szewc** [comment] 2017-10-24 15:51
@danieln100 no

**Comment by kumarse** [comment] 2017-10-24 16:59
I think this is related to: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2506

**Comment by pongad** [comment] 2017-10-24 23:49
I'm sorry I didn't see this; it must have slipped through triage.
There are two related issues.

1. The "idle stream" problem being tracked at #2506. I'm creating a PR for it today.

2. Even after (1) is fixed, sometimes the stream is terminated either by the server or because of some transient error. Nothing bad is happening; we'll just wait a few seconds then reconnect, but we logged it at SEVERE which is confusing. This was fixed by #2492 and released in 0.25.0

Since both are being addressed elsewhere, I'll close this issue as duplicate for now. Please reopen if you think they're unrelated.

**Closed by pongad** 2017-10-24 23:49 UTC

**Comment by k0ner** [comment] 2017-10-25 15:02
@pongad unfortunately what you are referring to (#2506) is the other problem we are facing (at least from what I understand). What we observed is that stream is reopened after throwing exception but it does not consume messages.

**Comment by pongad** [comment] 2017-10-26 04:02
@k0ner From the issue description, I conjecture that something like this is happening.

- we get no messages for a while
- stream disconnect
- someone publishes message
  - since we're disconnected, we don't see them
- transport layer eventually realizes we've disconnected
  - this is where we throw the exception
- reconnect
- consume all available messages
- repeat

If your topic is "low throughput", and a machine might not get any message for a few minutes at a time, it would make sense that this is caused by #2506.
On the other hand, if your machine regularly get messages and suddenly go silent, this would suggest that another problem is at play.
Can you let us know which scenario best describes your situation?

In the linked issue, I posted a command that you could run (on Linux) to get the kernel to perform keep-alive for us until we can get a permanent solution in place. Can you try it out and let us know if it helps?

**Comment by lukasz-szewc** [comment] 2017-10-26 07:56
@pongad can we assume that this will be resolved in 0.27.0-beta version of pubsub?

**Comment by wubolinha** [comment] 2018-08-27 08:41
I meet same question。。 how to solve it？

**Comment by Mistic92** [comment] 2018-08-27 09:04
What version are you using?

**Comment by SXerox007** [comment] 2018-12-21 12:31
Facing the same problem


implementation fileTree(dir: 'libs', include: ['*.jar'])
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.protobuf:protobuf-lite:3.0.0'
    implementation "javax.annotation:javax.annotation-api:1.2"

    implementation 'com.google.android.gms:play-services:+'

    implementation "com.google.api.grpc:proto-google-common-protos:1.0.0"
    implementation "io.grpc:grpc-alts:${grpcVersion}"
    implementation "io.grpc:grpc-netty:${grpcVersion}"
    implementation "io.grpc:grpc-protobuf:${grpcVersion}"
    implementation "io.grpc:grpc-stub:${grpcVersion}"

//    //gRPC needed
    implementation 'io.grpc:grpc-okhttp:1.12.0'

**Comment by suhasIVT** [comment] 2020-02-10 04:43
How to solve this error message ?
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason

**Comment by jstjyoti** [comment] 2020-12-29 09:30
io.grpc.StatusRuntimeException: UNAVAILABLE: no available workers Is the error I am facing after create remote buildfarm from buildfarm manager
