### ISSUE TITLE
Pub/Sub - "onStreamAllocated was not called" error under load

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#2042] opened 2017-05-09 03:26 UTC
Making continuous calls in a `while(true)` loop:
```
while (true) {
  String payload = String.valueOf(System.currentTimeMillis());         
  publisher.publish(PubsubMessage.newBuilder().setData(ByteString.copyFromUtf8(payload)).build());
```
Cases errors:
```
420)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:76)
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:71)
	at io.netty.handler.codec.http2.StreamBufferingEncoder$Frame.release(StreamBufferingEncoder.java:309)
	at io.netty.handler.codec.http2.StreamBufferingEncoder$DataFrame.release(StreamBufferingEncoder.java:357)
	at io.netty.handler.codec.http2.StreamBufferingEncoder$PendingStream.close(StreamBufferingEncoder.java:292)
	at io.netty.handler.codec.http2.StreamBufferingEncoder.writeRstStream(StreamBufferingEncoder.java:184)
	at io.grpc.netty.NettyClientHandler.cancelStream(NettyClientHandler.java:460)
	at io.grpc.netty.NettyClientHandler.write(NettyClientHandler.java:234)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:724)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1022)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:291)
	at io.grpc.netty.WriteQueue.flush(WriteQueue.java:127)
	at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:47)
	at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:59)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

When putting a slightest delay in the repeated call, the error goes away, e.g.
```
while (true) {
  String payload = String.valueOf(System.currentTimeMillis());         
  publisher.publish(PubsubMessage.newBuilder().setData(ByteString.copyFromUtf8(payload)).build());
  System.out.println(payload);
  // or Thread.sleep(100L)
```

**Comment by saturnism** [comment] 2017-05-25 05:46
quick ping

**Comment by pongad** [comment] 2017-05-25 07:55
@saturnism Sorry for the delay. I can't seem to replicate this problem. Using your code, the JVM runs out of memory in about 5 seconds, which makes sense considering what we're doing.

Are you running this on Linux?

**Comment by saturnism** [comment] 2017-06-08 22:54
I'm on OSX. See version info below.

I wonder what's taking up most of the heap, is it the Futures, or the message payload? I'm not entirely convinced that, for a simple fire and forget, we should run into OOM issues.


```
Darwin ... 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
```
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by pongad** [comment] 2017-06-09 01:07
> I'm not entirely convinced that, for a simple fire and forget, we should run into OOM issues.

I'm not sure what you mean. The `publish` method is asynchronous. It usually returns before the RPC has been completed. Since you can run through the loop a lot faster than the RPC can happen, your machine will OOM eventually.

@carl-mastrangelo Do you think the exception could be a GRPC issue? (You're the only name I know on grpc-java. Please let me know if I should direct these questions somewhere else!)

**Comment by carl-mastrangelo** [comment] 2017-06-09 04:10
Can the full error be included?  It looks like it got cut off.

In general, either the API needs to be able to push back on the caller (by blocking, for instance), or the caller needs to check whether the operation would block.  Queuing all the data results in OOM, so there needs to be some way of limiting this. 

If pubsub is calling the `isReady` or `setOnReadyHandler` on the `CallStreamObserver`, then my guess is that pubsub is not pushing back back against the application.  If it is _not_ calling those methods, it should!

**Comment by pongad** [comment] 2017-06-09 04:43
I think there are two separate issues. Rereading my response earlier, I realized I wasn't being clear. Apologies.

1. The OOM. I expected this issue. Pubsub team asked that Publisher intentionally does not push back against the application. We might add the push back feature later. This is definitely *not* a GRPC issue.

2. The stack trace. This I think might be caused by GRPC (we're using 1.2.0). IIUC, the only place `Publisher` makes RPC calls is [here](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/c4c80f54f707f4bce8debf17dd9fd475628e42f1/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/spi/v1/Publisher.java#L322)

**Comment by garrettjonesgoogle** [comment] 2017-08-10 20:52
Closing out because the requester has not provided the extra details necessary to investigate this problem, and also this is a "toy" problem (publishing the current time in a tight loop).

**Closed by garrettjonesgoogle** 2017-08-10 20:52 UTC
Labels: API: pubsub, Priority: P2+, Type: Bug
