### ISSUE TITLE
Firestore: DocumentReference#getCollections() should be async

### ISSUE THREAD

**Issue by samtstern** [GoogleCloudPlatform/google-cloud-java#2771] opened 2018-01-11 23:46 UTC
Most of the Firestore operations return `ApiFuture<T>`.  The method `DocumentReference#getCollections()` returns an `Iterable<CollectionReference>` but it should probably return `ApiFuture<Iterable<CollectionReference>>` since it calls over the network.

**Comment by samtstern** [comment] 2018-01-11 23:46
cc @schmidt-sebastian

**Comment by schmidt-sebastian** [comment] 2018-01-12 00:47
The ApiIterable class opens a network connection only when you first ask for data and not when the method executes. This behavior is similar to calling .get() on an ApiFuture.

**Comment by samtstern** [comment] 2018-01-12 00:50
Should we explicitly return `ApiIterable` to indicate that?  Or is that not the normal style?

**Comment by schmidt-sebastian** [comment] 2018-01-12 02:09
The Iterable is extracted from the `UnaryCallable` that the generated layer returns. It's signature is ` UnaryCallable<ListCollectionIdsRequest, ListCollectionIdsPagedResponse>`, which is not something I would like to impose on our users.

In the first pass of the review for this client, the method did in fact return an `ApiFuture<Iterable>`, but we changed it to just return an Iterable after initial comments (which I unsuccessfully tried to dig up).

**Comment by schmidt-sebastian** [comment] 2018-01-17 18:14
This works as intended. Closing.

**Closed by schmidt-sebastian** 2018-01-17 18:14 UTC
Labels: api: firestore, priority: p2, type: question
