### ISSUE TITLE
Docs have squashed text

### ISSUE THREAD

**Issue by craigcitro** [GoogleCloudPlatform/google-cloud-java#2706] opened 2017-12-13 18:53 UTC
An image says it all: 
<img width="555" alt="screen shot 2017-12-13 at 10 52 32 am" src="https://user-images.githubusercontent.com/468559/33956560-c5bf5bda-dff3-11e7-8eda-cdd4f7c53f5f.png">

This is on https://googlecloudplatform.github.io/google-cloud-java/0.32.0/index.html.

**Comment by garrettjonesgoogle** [comment] 2017-12-13 18:57
Duplicate of https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2663

**Comment by garrettjonesgoogle** [comment] 2017-12-20 22:45
This is fixed in code and should be fixed on the site in the next release.

**Closed by garrettjonesgoogle** 2017-12-20 22:45 UTC
