### ISSUE TITLE
Libraries with only an SPI layer are missing documentation

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/google-cloud-java#1536] opened 2017-01-13 20:16 UTC
# Issue
Documentation is missing for the most critical APIs for Java Cloud Vision.

## Repro
See [the Java documentation](http://googlecloudplatform.github.io/google-cloud-java/0.8.0/apidocs/index.html) and try to find the most important classes for the Cloud Vision API, most notably:

* com.google.cloud.vision.v1.AnnotateImageRequest
* com.google.cloud.vision.v1.AnnotateImageResponse
* com.google.cloud.vision.v1.BatchAnnotateImagesResponse
* com.google.cloud.vision.v1.ColorInfo
* com.google.cloud.vision.v1.DominantColorsAnnotation
* com.google.cloud.vision.v1.EntityAnnotation
* com.google.cloud.vision.v1.FaceAnnotation
* com.google.cloud.vision.v1.Feature
* com.google.cloud.vision.v1.Feature.Type
* com.google.cloud.vision.v1.Image

None of these features have documentation and are necessary to understand when using the Cloud Vision client library.

## Fix
Please generate and publish the documentation for the com.google.cloud.vision.* APIs.

It may also be helpful to include a nice little snippet demonstrating usage:

```
  public static void detectFaces(String filePath, PrintStream out) throws IOException {
    List<AnnotateImageRequest> requests = new ArrayList<>();

    FileInputStream file = new FileInputStream(filePath);
    ByteString imgBytes = ByteString.copyFrom(toByteArray(file));

    Image img = Image.newBuilder().setContent(imgBytes).build();
    Feature feat = Feature.newBuilder().setType(Type.FACE_DETECTION).build();
    AnnotateImageRequest request = AnnotateImageRequest.newBuilder()
        .addFeatures(feat)
        .setImage(img)
        .build();
    requests.add(request);

    BatchAnnotateImagesResponse response = visionApi.batchAnnotateImages(requests);
    List<AnnotateImageResponse> responses = response.getResponsesList();

    for (AnnotateImageResponse res : responses) {
      if (res.hasError()) {
        out.printf("Error: %s\n", res.getError().getMessage());
      }

      for (FaceAnnotation annotation : res.getFaceAnnotationsList()) {
        out.printf("anger: %s\njoy: %s\nsurprise: %s\n",
            annotation.getAngerLikelihood(),
            annotation.getJoyLikelihood(),
            annotation.getSurpriseLikelihood());
      }
    }
  }
```

**Comment by garrettjonesgoogle** [comment] 2017-01-13 20:42
* This affects all APIs which only have an spi layer. We are currently working on this.
* There are example apps here:

https://github.com/GoogleCloudPlatform/java-docs-samples

For Vision specifically:

https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/vision/text/src/main/java/com/google/cloud/vision/samples/text

I think there could be clearer pointers to the example apps.

**Comment by lesv** [comment] 2017-03-14 02:41
@gguuss PTAL - what you want appears done - please verify and close this.

**Comment by gguuss** [comment] 2017-03-14 17:44
We're still missing top-level links to reference documentation for the most important methods in Vision, Speech, and Natural Language.

As a specific example [in the 0.9.3 documentation](http://googlecloudplatform.github.io/google-cloud-java/0.9.3/apidocs/index.html), the package `com.google.cloud.vision.spi` appears in the package list but not `com.google.cloud.vision.v1`. For example, [com.google.cloud.vision.v1.Image](http://googleapis.github.io/googleapis/java/grpc-google-cloud-vision-v1/0.1.5/apidocs/com/google/cloud/vision/v1/Image.html) does not have links in the TOC on the JavaDoc site, navigating via the spi package to its documentation breaks navigation on the site.

I believe that these packages should appear in the package list alongside the spi packages and are probably more important than the SPI packages for developers trying to understand an API. We should try and make them discoverable via the package browser.

**Comment by garrettjonesgoogle** [comment] 2017-03-14 23:46
We have a problem because those classes are defined in a dependency, not within google-cloud-java itself. It doesn't seem like a good idea to include javadocs for types in another package. @lesv , what do you think?

**Comment by lesv** [comment] 2017-03-15 01:20
If it's something the user will need / want, we should either provided it or point them to the right place.

**Comment by garrettjonesgoogle** [comment] 2017-03-15 01:52
@lesv , we are already doing that - when users are looking at http://googlecloudplatform.github.io/google-cloud-java/0.9.4/apidocs/index.html?com/google/cloud/vision/spi/v1/ImageAnnotatorClient.html for example, they can click on the types in the function signatures and return types and they will navigate to the docs for them (e.g. http://googleapis.github.io/googleapis/java/grpc-google-cloud-vision-v1/0.1.6/apidocs/index.html?com/google/cloud/vision/v1/BatchAnnotateImagesRequest.html ). I think @gguuss 's problem is that when he is viewing types like the first, the "All Classes" list doesn't include types like the second, and vice versa. This is the same experience as with other types defined in other libraries, e.g. GAX types, Auth types, and JDK types.

**Comment by lesv** [comment] 2017-03-15 17:55
I looked at the docs, actually before my last post, and didn't see any of the com.google.... classes / methods / etc in the java docs. (ie. stuff w/o definition).  That's why I was asking @gguuss if it appeared correct in 0.9.4.  If not, could you give a specific example we can look at?

The link Gus gave to the [grpc-google-cloud-vision](http://googleapis.github.io/googleapis/java/grpc-google-cloud-vision-v1/0.1.5/apidocs/com/google/cloud/vision/v1/Image.html) API's isn't relevant to google-cloud-java.

**Comment by gguuss** [comment] 2017-03-15 23:13
Maybe I'm not being clear enough:

[Starting from the only vision API available from the JavaDoc content](http://googlecloudplatform.github.io/google-cloud-java/0.9.4/apidocs/index.html?com/google/cloud/vision/spi/v1/ImageAnnotatorClient.html):
![](http://wheresgus.com/toc_issue.png)

Click the link to the response from the API call:
![](http://wheresgus.com/link_to_orphan.png)

You are now in orphan territory:
![](http://wheresgus.com/orphan.png)

The difficult point is that the orphaned documentation is the most important documentation for the aforementioned APIs. We only are documenting the entry point.

From the external user perspective, **com.google.cloud.vision.spi.v1** and **com.google.cloud.vision.v1** are from the same source, their paths are the same and one is useless without the other. To conclude that because it's not internally, technically, the same, we should not have a browsable experience between them doesn't make sense to me. Customers will end up seeing the wrong half and will assume the docs are broken.

**Comment by lesv** [comment] 2017-03-16 01:42
I agree.

The problem is that they don't have the source -- probably should to be a veneer library.

[ImageAnnotatorClient](http://googlecloudplatform.github.io/google-cloud-java/0.9.4/apidocs/index.html?com/google/cloud/vision/spi/v1/ImageAnnotatorClient.html) should either link to [BatchAnnotateImagesRequest](http://googleapis.github.io/googleapis/java/grpc-google-cloud-vision-v1/0.1.6/apidocs/index.html?com/google/cloud/vision/v1/BatchAnnotateImagesRequest.html ) (wow poorly named) -- without that, it's very difficult for the user to know our organization.

I'm Ok with this not blocking release, but we should understand a solution.  This isn't the only place this will happen.

**Comment by gguuss** [comment] 2017-03-16 02:56
I'm also ok with this not blocking release as the docs are still getting published and once you understand the response objects are just in a separate place, the relevant docs are nested within the links from the .spi.v1 docs. It sounds like this can be closed as "will not implement" or "not feasible" and maybe we could track this as a feature request.

**Comment by garrettjonesgoogle** [comment] 2017-03-16 19:26
I will take the "release blocking" label off of this issue, but I think I will keep it open - we can track the request for showing exposed types from dependencies more prominently.

**Comment by tswast** [comment] 2017-05-04 23:08
I'm seeing some broken links.
http://googlecloudplatform.github.io/google-cloud-java/0.16.0/apidocs/com/google/cloud/pubsub/spi/v1/Subscriber.html

links to

http://googleapis.github.io/googleapis/java/grpc-google-cloud-pubsub-v1/0.1.9/apidocs/com/google/pubsub/v1/SubscriptionName.html?is-external=true

which does not exist.

**Comment by garrettjonesgoogle** [comment] 2017-05-04 23:11
@tswast This is fixed in 0.17.1 & later.

**Comment by tswast** [comment] 2017-05-04 23:12
Okay. I think I need to send out another docs CL to update some old links.

**Comment by tswast** [comment] 2017-05-04 23:12
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1883 can't come soon enough.

**Comment by garrettjonesgoogle** [comment] 2017-08-07 16:39
@tswast , https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1883 has been resolved.

**Comment by anthmgoogle** [comment] 2017-11-09 00:55
Is there still outstanding work before this can be closed after that resolution?

**Comment by hzyi-google** [comment] 2018-01-25 00:04
@garrettjonesgoogle is there still work to do for this issue? I am moving this to backlog and closing it, but if everything is resolved I will remove it from backlog then.

**Closed by hzyi-google** 2018-01-25 00:04 UTC
Labels: api: core, api: error reporting, api: language, api: monitoring, api: speech, api: vision, documentation, priority: p2, spi layer, type: feature request

**Comment by garrettjonesgoogle** [comment] 2018-01-25 00:10
The crux of this issue is that the requesters want the table of contents for the javadocs of google-cloud-java to include the proto-generated classes. I don't think this is really feasible, but the requesters really want it...
