### ISSUE TITLE
Hitting java.lang.NullPointerException error when a query taking a long execution time

### ISSUE THREAD

**Issue by 7sense** [GoogleCloudPlatform/google-cloud-java#1896] opened 2017-04-11 07:14 UTC
I am trying out the examples provided as below:

        QueryRequest request = QueryRequest.newBuilder(query)
                .setUseLegacySql(false) // standard SQL is required to use query parameters
                .build();
        QueryResponse response = bigquery.query(request);
        // Wait for things to finish
        while (!response.jobCompleted())
        {
            Thread.sleep(1000);
            response = bigquery.getQueryResults(response.getJobId());
        }

Because my query takes about 3 minutes to finish, I am getting the following error: (initially trigger at line "_response = bigquery.getQueryResults(response.getJobId());_")

	Exception in thread "main" java.lang.NullPointerException
		at com.google.cloud.bigquery.JobId.fromPb(JobId.java:97)
		at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:610)
		at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:594)

However, the query seems to be continuing running on the backend.
P.S. I am running a DELETE query.

**Comment by garrettjonesgoogle** [comment] 2017-04-12 21:26
This is a duplicate of https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1689 - follow the resolution there. Thanks!

**Closed by garrettjonesgoogle** 2017-04-12 21:26 UTC
Labels: API: bigquery
