### ISSUE TITLE
google-cloud-spanner: Add alternate r/w txn API that doesn't require use of callback

### ISSUE THREAD

**Issue by archiecobbs** [GoogleCloudPlatform/google-cloud-java#1627] opened 2017-02-15 14:23 UTC
In the Google Cloud Spanner Java API, the only way to perform read/write transactions is by providing a callback, via the `TransactionRunner` interface.

I understand that the API is trying to hide the details of the need to automatically retry transactions as a convenience to the programmer, but this limitation is a serious problem, at least for me. I need to be able to manage the transaction lifecycle myself, even if that means I have to perform my own retries (e.g., based on catching some sort of "retryable" exception, in this case `AbortedException`).

To make this problem more concrete, suppose one wanted to implement Spring's [PlatformTransactionManager](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/transaction/support/AbstractPlatformTransactionManager.html) for Google Cloud Spanner, so as to fit in with one's existing code, and use one's existing retry logic. It would not be possible with the current API.

It would be easy to augment the API in a backward compatible way, by adding a method returning a `TransactionContext` directly to the user, and let the user handle the retries. Of course this new method could be documented as "more dangerous and less convenient" to scare away noobs, etc.

Can this alternate (more traditional) transaction API style be added to the Java API?

Thanks.

**Comment by archiecobbs** [comment] 2017-02-17 00:07
Also please add the ability to get the commit timestamp from the transaction. There is currently no method `TransactionContext.getCommitTimestamp()`. Thanks.

**Comment by vkedia** [comment] 2017-03-24 22:32
@saturnism @emmanuelbernard This will be needed to implement [JTA](http://www.oracle.com/technetwork/java/javaee/jta/index.html) as well.

**Comment by vkedia** [comment] 2017-04-03 17:54
Closing this as this is duplicate of #1810

**Closed by vkedia** 2017-04-03 17:54 UTC
Labels: API: spanner, Type: Enhancement
