### ISSUE TITLE
Publish fail: Request threads can only be created within the context of a running request

### ISSUE THREAD

**Issue by gzc** [GoogleCloudPlatform/google-cloud-java#2058] opened 2017-05-12 16:33 UTC
Hi, I am using appEngine flexible environment with Java8. I am using pubsub0.17.1-alpha. When publishing, I will have this exception. I tried to run publish in a background thread but things are still same.

Following is the exception stack

```
WARNING: [io.grpc.internal.ManagedChannelImpl-1] 
Failed to resolve name. status=Status{code=UNKNOWN, description=null, cause=java.lang.IllegalStateException: Request threads can only be created within the context of a running request. 
at com.google.appengine.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:449) 
at com.google.apphosting.vmruntime.VmRequestThreadFactory.newThread(VmRequestThreadFactory.java:73)
at com.google.common.util.concurrent.ThreadFactoryBuilder$1.newThread(ThreadFactoryBuilder.java:162) 
at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612) 
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925) 
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368) 
at io.grpc.internal.DnsNameResolver.resolve(DnsNameResolver.java:205) 
at io.grpc.internal.DnsNameResolver.start(DnsNameResolver.java:116) 
at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:313) 
at io.grpc.internal.ManagedChannelImpl$4$1.run(ManagedChannelImpl.java:359) 
at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:87) 
at io.grpc.internal.ManagedChannelImpl$4.get(ManagedChannelImpl.java:361) 
at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:221) 
at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:47) 
at com.google.api.gax.grpc.HeaderInterceptor$1.start(HeaderInterceptor.java:62) 
at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:270) 
at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:249) 
at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:186) 
at com.google.pubsub.v1.PublisherGrpc$PublisherFutureStub.publish(PublisherGrpc.java:460) 
at com.google.cloud.pubsub.spi.v1.Publisher.publishOutstandingBatch(Publisher.java:333) 
at com.google.cloud.pubsub.spi.v1.Publisher.access$200(Publisher.java:76) 
at com.google.cloud.pubsub.spi.v1.Publisher$4.run(Publisher.java:271) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745)

```

Thanks^

**Comment by tcoffee-google** [comment] 2017-05-22 20:53
@gzc can you provide an example code snippet to help us reproduce the problem? Thanks!

**Comment by garrettjonesgoogle** [comment] 2017-06-02 20:13
@neozwu could you take a look?

**Comment by neozwu** [comment] 2017-06-06 04:51
Hi @gzc , I tested a GAE flex java 8 sample app with `publishOutstandingBatch` call (using google-cloud-pubsub-0.17.1-alpha), but cannot reproduce this error.  Can you provide more information to help repro?  I'd like to know in particular the dependency of your project, if possible, and how often you see this error. It is not clear to me why `ThreadFactoryBuilder` will end up using `VmRequestThreadFactory`.

**Comment by gzc** [comment] 2017-06-11 04:22
@neozwu Hi,
I do something trick to bypass using appengine ThreadFactory
```
System.clearProperty("com.google.appengine.runtime.environment");
```
Then I will use java default thread factory and it works.

My repo has too many dependencies, I will give more info later.

Thanks ^

**Comment by garrettjonesgoogle** [comment] 2017-07-17 21:28
I am going to close this issue because it appears that @gzc has a work around. Feel free to open if there are further issues.

**Closed by garrettjonesgoogle** 2017-07-17 21:28 UTC
Labels: API: pubsub, Priority: P1, running on app engine, Type: Bug
