### ISSUE TITLE
setMaxResults doesn't seem to work for Cloud Storage API

### ISSUE THREAD

**Issue by johanhaleby** [GoogleCloudPlatform/google-cloud-java#1511] opened 2017-01-06 12:34 UTC
I'm using:

```xml
<dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>gcloud-java</artifactId>
            <version>0.2.8</version>
</dependency>
```

which transitively depends on `com.google.apis:google-api-services-storage:v1-rev62-1.21.0` and I have the following code:

```java
Storage storage = ...
storage.objects().list(bucket).setMaxResults((long) Integer.MAX_VALUE).execute().getItems();
```

However the number of items are still 1000 (which is the default value) regardless of the value I pass to `setMaxResults`:

```java
System.out.println(storage.objects().list(bucket).setMaxResults((long) Integer.MAX_VALUE).execute().size());
```

This yields 1000 as result.

**Comment by garrettjonesgoogle** [comment] 2017-01-11 06:11
Could you try using a more recent version? The artifact is now named `google-cloud-java` and the latest version is `0.8.1`.

**Comment by johanhaleby** [comment] 2017-01-11 06:15
Oh I was unaware of the change of artifactId, thanks for the hint. I'll try to look into it in a few days if that's ok.

**Comment by johanhaleby** [comment] 2017-01-13 06:01
Is `google-cloud-java` in maven central? I can't seem to find it.

**Comment by garrettjonesgoogle** [comment] 2017-01-13 15:52
Oops sorry, the artifact is named `google-cloud`.

**Comment by garrettjonesgoogle** [comment] 2017-01-26 21:13
@johanhaleby , were you able to try out the new version?

**Comment by vam-google** [comment] 2017-01-31 02:09
Looks like it is by design. Though I agree, the API signature, naming and documentation are confusing.
Apparently Storage.setMaxResults() sets the maximum size for the results page, and the maximum allowed value for it is 1000 (not properly documented).

As a workaround the following code can be used (it will successfully read > 1000 objects, page by page):

```java
public class MyStorageExample {

  public static void main(String[] args) throws GeneralSecurityException, IOException {
    Storage.Builder sb = new Builder(
        GoogleNetHttpTransport.newTrustedTransport(),
        new JacksonFactory(),
        null);
    Storage storage = sb.build();

    Objects objects;
    String pageToken = null;
    final long maxPageSize = 0L; // 1000 is the maximum possible value
    final String bucketName = "<YOUR_BUCKET_NAME>";

    do {
      objects = storage
          .objects()
          .list(bucketName)
          .setMaxResults(maxPageSize)
          .setPageToken(pageToken)
          .execute();
      pageToken = objects.getNextPageToken();
      if(objects.getItems() != null) {
        System.out.println(objects.getItems().size());
      }
    } while (pageToken != null);
  }
}
```

**Comment by johanhaleby** [comment] 2017-02-02 06:23
@vam-google I'm using something similar to what you're describing. I think it would be nice to improve the docs a bit to make it clearer that 1000 is the maximum value. 

Thanks for the support everyone.

**Comment by vam-google** [comment] 2017-02-09 19:30
The documentation and default value was updated for the Storage API, and will be available in the never version, once it is released. Closing the issue.

**Closed by vam-google** 2017-02-09 19:30 UTC
Labels: blocking GA, storage
