### ISSUE TITLE
java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.

### ISSUE THREAD

**Issue by younas-bangash** [GoogleCloudPlatform/google-cloud-java#2526] opened 2017-10-14 10:06 UTC
I use below code in order to perform Face detection 

 ```
List<AnnotateImageRequest> requests = new ArrayList<>();
        ByteString imgBytes = ByteString.readFrom(new FileInputStream(filePath));
        Image img = Image.newBuilder().setContent(imgBytes).build();
        Feature feat = Feature.newBuilder().setType(FACE_DETECTION).build();
        AnnotateImageRequest request =
                AnnotateImageRequest.newBuilder().addFeatures(feat).setImage(img).build();
        requests.add(request);

        try (ImageAnnotatorClient client = ImageAnnotatorClient.create()) {
            BatchAnnotateImagesResponse response = client.batchAnnotateImages(requests);
            List<AnnotateImageResponse> responses = response.getResponsesList();

            for (AnnotateImageResponse res : responses) {
                if (res.hasError()) {
                    Log.d("Error: %s\n", res.getError().getMessage());
                    return;
                }

                // For full list of available annotations, see http://g.co/cloud/vision/docs
                for (FaceAnnotation annotation : res.getFaceAnnotationsList()) {
                    Log.d("getAngerLikelihood", ""+ annotation.getAngerLikelihood());
                    Log.d("getAngerLikelihood",""+annotation.getJoyLikelihood());
                    Log.d("getAngerLikelihood",""+annotation.getSurpriseLikelihood());
                    Log.d("getAngerLikelihood",""+annotation.getBoundingPoly());
                }
            }
        }

```

but I am facing the error 

[java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.](url)

**Comment by sceee** [comment] 2017-10-15 19:10
@younas-bangash probably a duplicate of #2398 , see that issue.

**Closed** 2017-10-15 19:52 UTC
