### ISSUE TITLE
google-cloud-bigquery 0.25.0-beta BigQueryClient throws java.lang.NullPointerException: Required parameter jobId must be specified. When performing dry run query. 

### ISSUE THREAD

**Issue by Tomczik76** [GoogleCloudPlatform/google-cloud-java#2479] opened 2017-10-04 14:29 UTC
google-cloud-bigquery 0.25.0-beta

BigQuery bigQuery = BigQueryOptions.getDefaultInstance.getService
QueryRequest request = QueryRequest.newBuilder(sql).setDryRun(true).setUseLegacySql(false).build()
bigQuery.query(request)

Throws  java.lang.NullPointerException: Required parameter jobId must be specified.

**Comment by Tomczik76** [comment] 2017-10-04 15:52
It seems that this regression started in 0.23.0, the last working version is 0.22.1

**Comment by akhilputhiry** [comment] 2017-12-03 01:54
I am also facing same issue. Even with `0.22.1` I am getting the error. Any workaround/fix for this.

**Comment by pongad** [comment] 2018-01-08 04:16
The exception is created from the lower-level autogenerated client. The problem seems to be that API definition requires that the field be set, but the server isn't setting it. I reached out to the BigQuery team to see what the intended behavior is here.

**Comment by pongad** [comment] 2018-01-10 23:42
This is a problem with BigQuery API description itself. I'll downgrade this to P2, since BQ team is tracking it at P2.

**Comment by nfallen** [comment] 2018-01-12 01:08
Hi, Big Query API team member here. The API description and the autogenerated client are working as intended. The root cause is that [BigQuery.query calls getQueryResults whether or not the query is a dry run.](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java#L599) A dry run does not actually execute a job, only validates it, so no job is created and no job ID will be returned in the API response. In this case it doesn't make sense to call getQueryResults, which looks up a particular job and thus requires a job ID. Thus, BigQuery.query should check that the job is not a dry run before calling getQueryResults.

**Comment by pongad** [comment] 2018-01-12 04:09
@nfallen You're right. I wasn't looking closely enough. Created PR to fix this.

**Comment by pongad** [comment] 2018-01-16 23:19
It's not possible to get rows from a dryrun, but the PR will make it more clear why it doesn't work.

**Closed** 2018-01-16 23:19 UTC
Labels: api: bigquery, priority: p2, type: bug
