### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.api.gax.rpc.StubSettings

### ISSUE THREAD

**Issue by tamersaleh** [GoogleCloudPlatform/google-cloud-java#2889] opened 2018-02-11 06:35 UTC
java.lang.ClassNotFoundException: com.google.api.gax.rpc.StubSettings
I just "exactly" followed this [link](https://cloud.google.com/logging/docs/reference/libraries)

**Comment by tamersaleh** [comment] 2018-02-11 06:38
I just have a simple questions, why almost "all" google APIs are not even working?

**Comment by pongad** [comment] 2018-02-12 02:54
@tamersaleh Could you share your `pom.xml` or `build.gradle`? This is most likely caused by dependency conflicts.

**Comment by tamersaleh** [comment] 2018-02-12 03:20
@pongad  thanks a lot for your prompt response :) 
I actually found Im using Firebase Admin dependence and it includes (by default) gaz, io.netty, google client api, I'd prefer that this firebase or any dependences to be stand alone, no need to include other depends unless it really cant even work without it 

After I exclude these dependencies from firebase it works :)

**Comment by pongad** [comment] 2018-02-12 03:25
@tamersaleh I'm glad this is working for you. The problem is similar to #2890. Since the immediate problem is resolved, I'll close this issue and track further action items there.

**Closed by pongad** 2018-02-12 03:25 UTC
Labels: dependencies, type: question

**Comment by mmaaww** [comment] 2018-09-03 05:27
Why Google Java API is always broken? Everytime upgrade takes days to find and fix bugs

**Comment by yyl719133368** [comment] 2019-05-23 15:32
Why Google Java API is always broken? Everytime upgrade takes days to find and fix bugs

**Comment by sduskis** [comment] 2019-05-23 16:35
@yyl719133368, can you please open a new bug, and give some details?
